### ISSUE TITLE
Not able to use some values with directional style

### ISSUE THREAD

**Issue by keshavmahawar** [jaredh159/tailwind-react-native-classnames#104]
Hi!!
Not able to use some values with directional styles (utility) like  `mt-0.25 mb-1.25` which is supported by height width and margins 
## Reason
in case of resolving from spacing `spacing.tsx` the value is returned null if not found in config
```javascript
    const configValue = config?.[value];
    if (!configValue) {
      return null;
    }
```
can we please have un-configured styles support in these spacing also, this would be really useful will make sense as they are already supported in other places also

**Comment by jaredh159** [comment]
yeah, this makes sense.  next time i sit down to do some work on this, I'll try to add support for that. thanks for the issue.

**Comment by jaredh159** [comment]
added support in `v2.2.0` 👍
