### ISSUE TITLE
Font family tailwind config expo

### ISSUE THREAD

**Issue by stefensuhat** [jaredh159/tailwind-react-native-classnames#107]
Hi 

Thanks for the helpful library. Is there a docs regarding how to properly implement font family using `tailwind.config.js`?

Currently I've tried this code but the it still showing default fonts

```
// tailwind.config.js

module.exports = {
  theme: {
    fontFamily: {
      sans: ['NotoSans', 'sans-serif'],
      serif: ['NotoSans', 'sans-serif'],
    }
  },
};

```

```
// App.tsx

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import tw from 'twrnc';
import Home from '~/screens/home';
import { useFonts } from 'expo-font';
import AppLoading from 'expo-app-loading';

export default function App() {
  let [fontsLoaded] = useFonts({
    'NotoSans': require('~/assets/fonts/NotoSans-Regular.ttf'),
  });
  
  if (!fontsLoaded) {
    return <AppLoading />;
  } else {
    return (
      <Home />
    );
  }
}

```

And I already did the customization part (import using custom tw lib)

Thanks.

**Comment by jaredh159** [comment]
@stefensuhat this library is only concerned with outputting the correct RN style objects, which it does correctly for font families (at least I think it does! -- lots of folks are using it that way, and there are unit tests covering the generation of font-family styles).  Ensuring that the font assets themselves are imported and working cross-platform is something you'll have to work out on your own, using the RN docs.  If it's helpful, here's a closed issue on the same subject:

https://github.com/jaredh159/tailwind-react-native-classnames/issues/13
