### ISSUE TITLE
useDeviceContext not working

### ISSUE THREAD

**Issue by Knaackee** [jaredh159/tailwind-react-native-classnames#108]
First, thanks for this great library.

I try to get breakpoints to work, so I call the `useDeviceContext` hook in my `App.tsx`. 
E.g. I tried to change the text color, but it doesn't work.

```
// App.tsx
const App = () => {
  useDeviceContext(tw);
  // ...
}
```

```
// Sample Screen
const Home = () => {
  return <View>
    <Text style={tw`text-pink-500 sm:text-yellow-400`}>Test</Text>
  </View>
}
```

Did I miss something?

**Comment by jaredh159** [comment]
Hard to say with just that much code, that all looks correct at first glance.  I'm guessing you're trying to test the fact that it goes to yellow at the `sm` media query?  What's your tailwind config look like?  Are you able to switch your device back and forth between that size and smaller to test?  

Another thing that can foul up the faux-media-queries is React.useMemo(), are you using that in your component hierarchy somewhere?

**Comment by Knaackee** [comment]
I found the problem. My config was broken. 

Thanks a lot for the quick help!

**Comment by lawrence615** [comment]
> I found the problem. My config was broken.
> 
> Thanks a lot for the quick help!

@Knaackee what was the issue with your config? Getting the same issue

**Comment by jaredh159** [comment]
@lawrence615 i've seen several people trip up doing a `export default` in their tailwind config, which doesn't seem to work, it seems you have to do `module.exports = `
