### ISSUE TITLE
Support fontSize using with vw and vh unit

### ISSUE THREAD

**Issue by truongtv22** [jaredh159/tailwind-react-native-classnames#113]
I am having problems when I want to use vw unit with fontSize
```
console.log(tw.style("text-[10vw]"));
// { color: "10vw" }
```

**Comment by jaredh159** [comment]
yeah, currently not supported, but it's easy to add, I've got a branch going where i have support added, will get a release out shortly with the new feature. thanks for the issue.

**Comment by jaredh159** [comment]
pushed a new version with this, `2.3.0`

**Comment by truongtv22** [comment]
Thank you
