### ISSUE TITLE
Problems with standard color styles

### ISSUE THREAD

**Issue by ian** [jaredh159/tailwind-react-native-classnames#114]
We keep running into issues with very common class styles:

```
`border-gray-400` is not a valid Tailwind class name
at node_modules/tailwind-react-native-classnames/dist/tailwind.js:38:16 in classNames.forEach$argument_0
at node_modules/tailwind-react-native-classnames/dist/tailwind.js:24:8 in getStyle
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:6 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:655:10 in setTimeout$argument_0
```

This is both with and without tailwind.config.js theme color overrides.

This should absolutely be a color style, any idea why this is failing?

**Comment by mazino-dev** [comment]
I had similar issues with some other class names, cant remember which. To circumvent this, I am currently using _tw.style([], {})_ format, colors are imported from a object representing theme of the app and go against react native component's properties in the second argument to the function, while first argument contains the usual tailwind class names. Made it a little easier to modify the colors in a single place. But maybe same could be done with string interpolation of typescript, except met same error in one or more of the colors I am using for my personal app.

**Comment by ian** [comment]
Sounds like a good workaround, wish it didn't need to happen but at this point I'll take it.

**Comment by jaredh159** [comment]
@ian  can you paste in your tailwind config? if that color is a supported color in your config, it should absolutely just work, and we have lots of tests covering that use case.  i'm curious why it's not working for you.

**Comment by ian** [comment]
@jaredh159 thanks, I ended up solving the problem, was on our side. My junior dev imported the tailwind styles incorrectly and it was missing some of the core classes.

Thanks for your help, all is good now that we fixed the initialization. Closing this.
