### ISSUE TITLE
Arbitrary values for flex?

### ISSUE THREAD

**Issue by x-ji** [jaredh159/tailwind-react-native-classnames#115]
I needed to manually specify `flex: 0.2` on an item, but couldn't find a way to do it with twrnc. I thought it might be `flex-[0.2]` as seen on [this page](https://tailwindcss.com/docs/flex) but it seems to not be supported yet. Or maybe I was looking at the wrong property.

**Comment by semoal** [comment]
Is not available on this lib yet, I'm sure that if you create a pull request @jaredh159  will merge it :)

**Comment by semoal** [comment]
Just checked the code and this is available:

```tsx
      // arbitrary
      [`flex-33`, { flexGrow: 33, flexBasis: `0%` }, null],

```

Just try: `flex-0.2` probably will work

**Comment by jaredh159** [comment]
@x-ji I just checked and `flex-0.2` does not currently work (it currently only supports non-_decimal_ arbitrary values), but I made a quick patch to allow it to support all numbers.  I'll get a release out shortly and update the issue when i do.  Thanks for the issue.

**Comment by jaredh159** [comment]
pushed a new version with this, `2.3.0`

**Comment by x-ji** [comment]
Thanks a lot for the prompt fix!
