### ISSUE TITLE
Do Tailwind CSS plugins work with twrnc?

### ISSUE THREAD

**Issue by Natetronn** [jaredh159/tailwind-react-native-classnames#118]
I was trying twrnc with [daisyui](https://daisyui.com), which is a tailwind css plugin. I wasn't able to get it working and thought I better check if Tailwind CSS plugins work with twrnc?

I created a [twrnc / daisyui codesandox](
https://codesandbox.io/s/twrnc-daisyui-3tmmb), of what I think is the proper setup but, I'm getting the following error in the sandbox:

`tailwindcss plugin function argument object prop "daisyui.logs" not implemented
`

Locally I'm getting a slightly different error, which I've trimmed a bit for readability (I can add the full log if need be):

```
 ERROR  TypeError: undefined is not a function (near '...pluginFn...') 
...
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "../lib/tailwind").tw')
...
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "../lib/tailwind").tw')
```

Any thoughts by chance?

**Comment by Natetronn** [comment]
Dang, forgot to search first, sorry! Looks like others are trying to do the same thing:

https://github.com/jaredh159/tailwind-react-native-classnames/issues/55

https://github.com/jaredh159/tailwind-react-native-classnames/issues/29

**Comment by Natetronn** [comment]
We're already kind of being lazy (aka smart?) by using Tailwind CSS. Something like Daisy UI seemed like another step in that direction, at least for this personal project of mine where I can get away with using whatever I want.

With that, I am curious what your thoughts on something like Daisy UI are, say, if someone was to split it apart for RN or to take a similar concept (with all the @apply work done etc.) and prune it, do you think people would want something like that?

I've seen a couple issues here in the repo where people were asking for a bit more support for the RN Web and you mentioned splitting the code base into a "core" and a "web". Would doing that allow someone to split something like Daisy in parts so it's available for all three, RN, RN Web and React, all at the same time? 

Note: I realize splitting those doesn't necessarily rely on you splitting twrnc, just kind of thinking out load here about what such a landscape would looks like, where a single UI framework could be use across multiple platforms etc.

Any thoughts?

Anyway, going to close this out.

**Comment by jaredh159** [comment]
@Natetronn yeah, i'm not really sure. I've advised people in the past not to try to use DaisyUI with twrnc, because it's emphatically a web-focused framework, and this library doesn't try to cover all the web utilities that one might want to use with RN web.

theoretically, if I, or someone else ever built a library to layer on support for all of the web utilities, compatibility with DaisyUI for RN web might be possible.  Although it might take some work also in the plugin layer -- right now we just support a very limited subset of functionality, enough to allow folks to define custom utilities for RN native projects.

**Comment by Natetronn** [comment]
Thanks for the reply, @jaredh159!
