### ISSUE TITLE
new color name is not exist in v3

### ISSUE THREAD

**Issue by chinieer** [jaredh159/tailwind-react-native-classnames#119]
for example,when i use new 'zinc-700' ,it warns unknown or invalid utility

**Comment by jaredh159** [comment]
can you paste in your tailwind config? are you sure you've got that color enabled? also, make sure you have tailwind v3 installed, not v2.

**Comment by chinieer** [comment]
> can you paste in your tailwind config? are you sure you've got that color enabled? also, make sure you have tailwind v3 installed, not v2.

thanks for reply, i found the reason that  using 'yarn add twrnc' to install  the dependence version of  tailwind is  "2.2.19" in yarn.lock , it can be reproduce  anytime

**Comment by jaredh159** [comment]
yeah, you're right, i meant for it to be `>=2.0.0`, not `^=2.0.0`.  Updated and released `v3.0.1`, thanks for bringing this to my attention.
