### ISSUE TITLE
Custom classnames "unknown or invalid utility"

### ISSUE THREAD

**Issue by gamble23** [jaredh159/tailwind-react-native-classnames#121]
Hi, i already saw the closed issue #99 and right now i facing the same problem.

I created my **_tailwind.config.js_** file inside root and added this:

```javascript
const { plugin } = require('twrnc'); 

module.exports = {
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        test: {
          backgroundColor:  "red",
        },
      });
    }),
  ],
};
```

And then try to use it:
```jsx
<ScrollView style={tw`test`}>
  <Text>Test</Text>
</ScrollView>
```

Still getting this error 
`"test" unknown or invalid utility`

I created my App with expo wich seems to use this version of react native`"react-native": "0.64.3"`
My node version is (16.13)

Anything that i forgot or misunderstood? I hope someone can help me.

**Comment by jaredh159** [comment]
@gamble23 that should definitely work.  I just copied your code into a sample app (also an expo) app, and it worked perfectly.  Maybe paste in your whole tailwind config file so I can take a look? Or is the project open source?

**Comment by gamble23** [comment]
Hi @jaredh159 

i prepared a minimal setup here: https://github.com/gamble23/rn-test 

Something i missing? Still getting the error.

**Comment by jaredh159** [comment]
the library doesn't know about your tailwind config unless you specify it's location and create your own version of the `tw` function, configured.  this is described in the "Customization" section of the readme:

https://github.com/jaredh159/tailwind-react-native-classnames#customization

**Comment by gamble23** [comment]
@jaredh159 I knew i forgot something... Works perfectly now!

Thank you so much for your help and this great package!
