### ISSUE TITLE
some warnings come from tailwind

### ISSUE THREAD

**Issue by chinieer** [jaredh159/tailwind-react-native-classnames#122]
tailwind CSS version: 3.0.18
tailwind-react-native-classname version: 3.0.1 
it seems a tailwind bug but has solved in https://github.com/tailwindlabs/tailwindcss/issues/7210 , but it still happens in tailwind-react-native-classname
![image](https://user-images.githubusercontent.com/5187043/151920212-c1ef3fbd-af01-43a8-8402-af8446f6e2a2.png)

**Comment by jaredh159** [comment]
i assume you have a `content` prop in your tailwind config?

**Comment by chinieer** [comment]
> i assume you have a `content` prop in your tailwind config?

i import it without customize config file just use directly

**Comment by chinieer** [comment]
i found the warnings was introduced in https://github.com/tailwindlabs/tailwindcss/pull/7065

**Comment by LivingInLimbo** [comment]
I'm getting this issue even with the "content" prop in my tailwind.config.js. Here's what it looks like: 
`module.exports = {
  content: ["./pages/**/*.{html,ts}", "./components/**/*.{html,ts}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
`

**Comment by Klin-Coders** [comment]
any solution yet?

**Comment by jaredh159** [comment]
I'm away from my office for a while, without my normal computer and with really poor internet, but I _think_ I know what might be causing these warnings, and I cooked up a quick beta release to test my theory.  Could one or more of you give it a test and report back? To install, run:

```bash
npm install twrnc@next
```

@chinieer @LivingInLimbo @Klin-Coders

**Comment by chinieer** [comment]
> I'm away from my office for a while, without my normal computer and with really poor internet, but I _think_ I know what might be causing these warnings, and I cooked up a quick beta release to test my theory. Could one or more of you give it a test and report back? To install, run:
> 
> ```shell
> npm install twrnc@next
> ```
> 
> @chinieer @LivingInLimbo @Klin-Coders

has solved! thank you for all you did

**Comment by jaredh159** [comment]
@chinieer thanks for reporting back.  just released `3.0.2` which contains the fix.

**Comment by LivingInLimbo** [comment]
Do I have to change my package.json if I installed the beta release? Fixed the warnings for me as well.

**Comment by amitkrsrswt** [comment]
warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration
    tailwindcss": "^3.0.19
plz somebody help

**Comment by jaredh159** [comment]
What version of twrnc are you on? You shouldn’t have that error if you’re on the latest.

**Comment by aacassandra** [comment]
@jaredh159 , same here
im using tailwind 3.0.24

**Comment by jaredh159** [comment]
@aacassandra what version of `twrnc` (not tailwindcss) are you running?
