### ISSUE TITLE
Change Colors at Runtime

### ISSUE THREAD

**Issue by riteshdalal** [jaredh159/tailwind-react-native-classnames#126]
Is it possible to change the color "Theme" at runtime.. Like we are able to do in the web by overriding the CSS variables? 

For example: We want to update the look of the app based on the logged in user and on logout, it resets to the default theme.

**Comment by jaredh159** [comment]
There's no built-in way to do this.  You could probably figure out a way to pull it off, maybe by using some shared set of variables like:

```js
class Theme {
  static primary = `blue-400`
  /* etc... */
}

tw`bg-${Theme.primary}`
```

You'd just need to ensure that something triggers a re-render when you switch themes.  There might be a more elegant way to accomplish it, I just can't think of it right now.

**Comment by riteshdalal** [comment]
Thanks @jaredh159  

we tried a few things and figured a way which was a little seamless. Like creating and new tailwind config file that has named colors like this and then generate a new tw object using the create function and storing it in a redux store for use across components. So Al components are always using the latest tw. And we can replace that object in the redux store when theme changes. 

Do you see any issues with that approach?

**Comment by jaredh159** [comment]
That seems like it would work fine. I was thinking a little bit along the same lines, if you had some sort of _context_ to supply the theme (which is what Redux uses under the hood), that would probably work nicely, as long as something triggered a re-render when the theme changes, which shouldn't be hard to accomplish.
