### ISSUE TITLE
Argument of type 'StyleProp<ViewStyle>' is not assignable to parameter of type 'ClassInput'.

### ISSUE THREAD

**Issue by mahdisalehian** [jaredh159/tailwind-react-native-classnames#128]
My twrnc package version: 3.0.1

Here is my code:
```
interface IBottomBoxRowProps extends ViewProps{}

const BottomBoxRow: FC<IBottomBoxRowProps> = ({ style, children, ...rest }) => {
  return (
    <View style={tw.style('flex-row', style)} {...rest}>
      {children}
    </View>
  );
};
```
And I got this error:
```
Argument of type 'StyleProp<ViewStyle>' is not assignable to parameter of type 'ClassInput'.
  Type 'RegisteredStyle<ViewStyle>' is not assignable to type 'ClassInput'.
    Type 'RegisteredStyle<ViewStyle>' is not assignable to type '{ [k: string]: string | number | boolean; }'.
      Index signature for type 'string' is missing in type 'Number & { __registeredStyleBrand: ViewStyle; }'
```
How can I fix this issue?

**Comment by jaredh159** [comment]
yeah, the type for the inputs to the `tw` function are not perfectly complete. they cover almost all the use-cases of constructing style objects by hand, but when you pass a type from RN or a library, they sometimes complain when they shouldn't. 

at this point, the workaround is just to cast to `any`: `tw.style('flex-row', style as any)`.  Not ideal, i know, but usually not a major problem.  I probably should try to improve the types for these sorts of situations to accept RN style props.  But that's the way it is now.

**Comment by heondo** [comment]
> My twrnc package version: 3.0.1
> 
> Here is my code:
> 
> ```
> interface IBottomBoxRowProps extends ViewProps{}
> 
> const BottomBoxRow: FC<IBottomBoxRowProps> = ({ style, children, ...rest }) => {
>   return (
>     <View style={tw.style('flex-row', style)} {...rest}>
>       {children}
>     </View>
>   );
> };
> ```
> 
> And I got this error:
> 
> ```
> Argument of type 'StyleProp<ViewStyle>' is not assignable to parameter of type 'ClassInput'.
>   Type 'RegisteredStyle<ViewStyle>' is not assignable to type 'ClassInput'.
>     Type 'RegisteredStyle<ViewStyle>' is not assignable to type '{ [k: string]: string | number | boolean; }'.
>       Index signature for type 'string' is missing in type 'Number & { __registeredStyleBrand: ViewStyle; }'
> ```
> 
> How can I fix this issue?

Cant you use an array instead?

```
<View style={[tw('flex-row'), style]}>
```

**Comment by jbcrestot** [comment]
@jaredh159 Could you also add Animated.AnimatedProps<ViewStyle> to ClassInput type? otherwise, animation props aren't valid.

**Comment by jaredh159** [comment]
today i took a whack at trying to improve the types to accommodate `StyleProp<ViewStyle>` and friends, and realized it's not just a typing deficiency. a `StyleProp<ViewStyle>` might be an **array** of style props, or a recursive array, and the library is not designed (currently) to handle those. 

so, in hindsight casting to `any` is bad advice -- it might work a lot of the time, but you could get some input that breaks all of our assumptions and possibly produces a runtime error.

i think i'm comfortable saying that the library does not accept arbitrary style props from other components, or from libraries. rather, the object-form of style prop is meant for hand-authored customizations and overrides.
