### ISSUE TITLE
Question regarding custom fontFamily

### ISSUE THREAD

**Issue by hugefunwoo** [jaredh159/tailwind-react-native-classnames#13]
Thanks for this great tool!

Not sure if I did it right, my `tailwind.config.js` which has following custom fontFamily setting but it's not compiled to corresponding font utility like `font-sans`

```
module.exports  = {
  theme: {
    fontFamily: {
      sans: ['NotoSansTC', 'sans-serif'],
    }
  }
};

**Comment by jaredh159** [comment]
hmm.... in my projects i've not used tailwind classes for font families, so I'm not sure if there's a bug in this package, or if it's just never been supported/implemented.  i'll make a note to poke around soon and see if it's easy to fix or support, and get back to you.

**Comment by hugefunwoo** [comment]
Thanks @jaredh159 !

For people who needs font family utility you can add a custom JSON file like below

```
import { create } from 'tailwind-react-native-classnames';

import styles from '../../tw-rn-styles.json';
import customFont from '../../tw-rn-styles-custom-font.json';

export default create({ ...styles, ...customFont });
```

// in tw-rn-styles-custom-font.json
```
{
  "font-sans": {
    "fontFamily": "NotoSansTC-Regular"
  }
}
```

**Comment by jaredh159** [comment]
@hugefunwoo I think I was able to successfully add built-in support for these utilities.  I released a beta version `1.3.0-beta.1`.  Would you mind testing to see if it's working for you?

```bash
npm install tailwind-react-native-classnames@1.3.0-beta.1
```

**Comment by hugefunwoo** [comment]
awesome, it works like a charm  Thanks @jaredh159

**Comment by jaredh159** [comment]
Thanks for testing @hugefunwoo. I did a little testing of my own, and seems fine.  Released `1.3.0` as well.

**Comment by raquelmsmith** [comment]
@hugefunwoo if you don't mind, how did you import the font files that you want to use?

Also related and maybe a question for @jaredh159 , what's the workflow for editing `tailwind.config.js` when I want to add these customizations?

**Comment by hugefunwoo** [comment]
Hi @raquelmsmith! not sure if I get the question 100% but we added it in ios/yourawesomeapp/Info.plist like below

```
<string>NotoSansTC-Bold.otf</string>
```

**Comment by jaredh159** [comment]
@raquelmsmith I've never imported a custom font file into an iOS/android app, but I would google for some documentation from RN or elsewhere.  good luck!

**Comment by raquelmsmith** [comment]
OK in short to add the custom font files to RN: 
- Add .ttf font files to `./asets/fonts`
- Run `npx react-native-link`
- Then include in `tailwind.config.js` as @hugefunwoo posted initially
- Run `npx trnc-create-styles`
- Rebuild your app

The biggest issue remaining is that this works great on iOS with variable font weights, meaning you can just use the font family name and iOS can handle `font-weight: 700` and pick the right one. Android... not so much. It wants you to tell it _exactly_ which font file to use. 

The best idea I've come up for this is to define each weight in `tailwind.config.js` like:

```
module.exports  = {
  theme: {
    fontFamily: {
      sans: ['Inter', 'sans-serif'],
      sans-bold: ['Inter-Bold', 'sans-serif'],
      sans-extrabold: ['Inter-Extrabold', 'sans-serif'],
    }
  }
};
```

Not really an ideal solution. I'm also not sure if it will work on iOS, need to test that. Any other brilliant ideas?

**Comment by jaredh159** [comment]
thanks for posting your findings.  i don't have any brilliant ideas, sadly.  RN development is full of weird quirks and edge-cases like this. 😕

**Comment by raquelmsmith** [comment]
No new insights, except that it has worked well for me.

To disable the weights, in your tailwind config file just remove all values for fontWeight (or add an empty object if your config file is empty). I'm not in my codebase right now (on my phone) so I can't give an example but you can see the docs here: https://tailwindcss.com/docs/font-weight (see "customizing your theme" at the bottom)

More info: https://tailwindcss.com/docs/theme

**Comment by crherman7** [comment]
Agreed, this is an obnoxious edge case presented by react native. I've used a combination of @raquelmsmith solution + a custom directive implemented by hijacking `react.createElement` so that I can sanitize the tailwind styles. I have to sanitize the styles because `font-mono-bold font-bold` will work for iOS but not for Android - so I sanitize the default font-weights provided by tailwind for android only via `lodash-es` `pullAll`.

```
  const originalCreateElement = react.createElement.bind(react);

  react.createElement = ((
    type: any,
    props?: Record<string, any> | null,
    ...children: React.ReactNode[]
  ) => {
    let {styleName} = props ?? {};

    if (styleName) {
      const tailwindFontWeights = [
        'font-thin',
        'font-extralight',
        'font-light',
        'font-normal',
        'font-medium',
        'font-semibold',
        'font-bold',
        'font-extrabold',
        'font-black',
      ];
      if (Platform.OS === 'android') {
        styleName = pullAll(styleName.split(' '), tailwindFontWeights);
      }

      props = {...props, style: tw.style(styleName, props?.style)};
    }

    return originalCreateElement(type, props, ...children);
  }) as typeof React['createElement'];
```

**Comment by coryoso** [comment]
I found a good way by overwriting the styles generated when rendering the Text, inspired by [this project](https://github.com/Ajackster/react-native-global-props/blob/master/src/CustomFunctions/setCustomText.js)

Import the file into your `index.js` before loading the app, like this `import "./src/utils/fixFonts"`. Overwrite the `fontForWeight` function with your custom font names.

```
/* eslint-disable @typescript-eslint/ban-ts-comment */
import { Text } from "react-native"

// inspired by: https://github.com/Ajackster/react-native-global-props/blob/master/src/CustomFunctions/setCustomText.js

const fontForWeight = (weight?: string) => {
	switch (weight) {
		case "500":
			return "Inter-Medium"
		default:
			return "Inter-Regular"
	}
}

// @ts-ignore
const TextRender = Text.render

// @ts-ignore
Text.render = function render(props) {
	const oldProps = props
	props = { ...props, style: props.style ?? {} }

	props.style.fontFamily = fontForWeight(props.style.fontWeight)

	try {
		// @ts-ignore
		// eslint-disable-next-line prefer-rest-params
		return TextRender.apply(this, arguments)
	} finally {
		props = oldProps
	}
}
```
