### ISSUE TITLE
Is there an equivalent to gap-{number} ?

### ISSUE THREAD

**Issue by FredericoGauz** [jaredh159/tailwind-react-native-classnames#130]
Hi, really thank you for this amazing library that will save us hours of styling!

It might be a silly question, but is there a way to use something like: "flex flex-row gap-2" ?

Thanks!

**Comment by jaredh159** [comment]
Not a silly question, thanks for asking.

So, this library currently only aims to support the utilities in tailwindcss that are _also_ supported as style props in React Native (not web).  I don't see that RN native supports any of the flexbox "gap" functionality, and they don't support css grid at all, so even if i was to implement these utilities, they would have no effect in an RN project.

some people are using this library for RN Web, and it works fine for the utilities that it supports, but as of now there are no immediate plans to expand coverage for RN web.  you can see the [discussion here](https://github.com/jaredh159/tailwind-react-native-classnames/discussions/125) for more context.

**Comment by FredericoGauz** [comment]
Hi Jared,

Thank you for your reply. I understand now, I think it makes sense!
