### ISSUE TITLE
Inconsistent behavior of styles on ios and android 

### ISSUE THREAD

**Issue by 1finedev** [jaredh159/tailwind-react-native-classnames#131]
styles like `border border-dotted` doesn't even appear on ios and styles like `shadow-md` behaves funny on android and doesnt work on ios 

is there anything i am doing wrong?

**Comment by jaredh159** [comment]
I'd have to see your code to know for sure, but I can tell you that these utilities do work.  A couple thoughts though:

1. The `shadow-md` class that is built-in to the library tries to mimic the Tailwindcss shadow, which is _very subtle_, so it's easy to miss.  You can customize the shadow as described in the readme to make it more visible. Look at the picture below, the `shadow-md` is there, it's just very light. Again, this is customizable.
2. I'm not sure what you mean by "behaves funny on android", but remember, android only supports an `elevation` prop, so you're not going to get an exact match between the platforms. Check out the section on shadows in the readme for more info.
3. Borders (especially dotted) can be hard to see, maybe try to make the width larger with `border-2` or something like that.

For example, the below code:

```tsx
export default function App() {
  return (
    <View style={tw`flex items-center justify-center h-screen`}>
      <View style={tw`p-5 bg-blue-100 shadow-xl border border-2 border-dotted mb-6`}>
        <Text style={tw`text-xl`}>With shadow-xl</Text>
      </View>
      <View style={tw`p-5 bg-blue-100 shadow-lg border border-2 border-dotted mb-6`}>
        <Text style={tw`text-xl`}>With shadow-lg</Text>
      </View>
      <View style={tw`p-5 bg-blue-100 shadow-md border border-2 border-dotted mb-6`}>
        <Text style={tw`text-xl`}>With shadow-md</Text>
      </View>
      <View style={tw`p-5 bg-blue-100 border border-2 border-dotted mb-6`}>
        <Text style={tw`text-xl`}>No shadow</Text>
      </View>
    </View>
  );
}
```

Renders like this on iOS:

![Screen Shot 2022-02-18 at 9 38 05 AM](https://user-images.githubusercontent.com/7050938/154703149-256edc73-169a-4544-a756-195ec2354c81.png)
