### ISSUE TITLE
Custom colors supported?

### ISSUE THREAD

**Issue by sp-cmingay** [jaredh159/tailwind-react-native-classnames#132]
`"twrnc": "^3.0.2"`

First off thanks for all of your effort with this, I'm just getting started with React native and am already a fan of Tailwind!

If I specify some custom colours in `tailwind.config.js` via the extend section should I be able to use them with twrnc for text colour? e.g. `text-sp-purple`

The "Home Screen" text doesn't seem to get styled, however if I change
```
<Text style={tw`text-sp-purple`}>Home Screen</Text>
```
 to 
```
<Text style={tw`text-red-500`}>Home Screen</Text>
```

 it displays as expected.

**tailwind.config.js**

```
export default {
    content: ["./**/*.{html,js}"],
    theme: {
        extend: {
            animation:{
                'background-scroll': 'background-scroll 10s ease infinite', // ease
            },
            keyframes: {
                'background-scroll': {
                    '0%, 100%': { backgroundPosition: '0% 50%', backgroundSize: '300% 200%'},
                    '50%': { backgroundPosition: '100% 50%;'}
                }
            },
            colors: {
                'sp-red': '#E5202F',
                'sp-orange': '#F06424',
                'sp-yellow': '#FAA51A',
                'sp-purple': '#9E07AE',
                'sp-black': '#000000',
                'sp-white': '#FFFFFF',
                'sp-dark-gray-75': '#444444',
                'sp-dark-gray-50': '#5A5A5A',
                'sp-dark-gray-25': '#6F6F6F',
                'sp-mid-gray': '#9B9B9B',
                'sp-light-gray-75': '#C6C6C6',
                'sp-light-gray-50': '#E2E2E2',
                'sp-light-gray-25': '#F2F2F2',
            },
        },
    },
  }
```

**lib/tailwind.js**

```
import { create } from 'twrnc';
const tw = create(require(`../tailwind.config.js`));
export default tw;
```

**screens/home.js**

```
import {Button, Text, View} from "react-native";
import React from "react";
import tw from '../lib/tailwind';

function HomeScreen({navigation }) {
    return (
        <View style={tw`flex-1 items-center justify-center min-h-screen`}>
            <Text style={tw`text-sp-purple`}>Home Screen</Text>
            <Button
                title="Go to Details"
                onPress={() => navigation.navigate('Details')}
            />
        </View>
    );
}

export default HomeScreen;
```

**Comment by jaredh159** [comment]
hmmm.... it might be because of all the dashes in your color names. there's a little bit of ambiguity dealing with dashes in colors, because of color default values and numbered sub-variants.  can you try a quick experiment and remove all the dashes and see if it works?

if it does, let me know, i'm not saying that's the long term solution necessarily, i might need to make the color parsing logic more nuanced.

**Comment by sp-cmingay** [comment]
Blimey, quick response!

Still no luck unfortuantely

** tailwind.config.js **
```
export default {
    content: ["./**/*.{html,js}"],
    theme: {
        extend: {
            colors: {
                'spred': '#E5202F',
            },
        },
    },
  }
```

**screens/home.js**
```
<Text style={tw`text-spred`}>Home Screen</Text>
```

**Comment by jaredh159** [comment]
strange, that should definitely be working.  any chance your project is open source so i could check it out? or could you make a minimal repro?

**Comment by sp-cmingay** [comment]
Sure thing  - https://github.com/sp-cmingay/twrnc-colors

I created the above with...

```
expo init twrnc-colors
cd twrnc-colors
npm start
```

I note when installing twrnc with `npm install twrnc` that it complains about peer dependencies (tailwind needs autoprefixer and autoprefixer needs postcss) however even if I meet these dependencies before attempting to install twrnc I get the same.

Thanks again!

**Comment by jaredh159** [comment]
just pulled down your repro repository. i've seen this one other time, and i can't tell you why, but it fixes it to do a commonjs style `module.exports = ` in your `tailwind.config.js`.  For some reason changing that to `export default` causes it to not work.  All of the tailwindcss documentation shows the file with `module.exports = `, fwiw.

see my PR here: https://github.com/sp-cmingay/twrnc-colors/pull/1

**Comment by sp-cmingay** [comment]
Got ya, thank you very much for taking the time to look in to it
