### ISSUE TITLE
Unknown or invalid utility error

### ISSUE THREAD

**Issue by adnan-SM** [jaredh159/tailwind-react-native-classnames#134]
I am trying to customise colors for my projects using a custom `tailwind.config.js` but I seem to be getting an invalid utility error. 

Here is my tailwind config file: 

```
module.exports = {
  extend: {
    theme: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        adn: '#ffffff',
        white: '#ffffff',
        primary: '#859ACA',
        secondary: '#9DB7CD',
        accent: '#01BFBD',
      },
    },
  },
};
```

I then export the custom config using `create`. Code for the same: 

```
import {create} from 'twrnc';

const config = require('../tailwind.config.js');
const tw = create(config);
export default tw;

```

Finally trying to use it in a component like below: 

```
import {Text} from 'react-native';
import React from 'react';
import tw from '../lib/tailwind';

export default function LoginScreen() {
  return <Text style={tw`bg-black text-2xl text-primary`}>Hi</Text>;
}

```

I keep getting the invalid utility error when I try to run this. Any ideas what I am doing wrong?

**Comment by jaredh159** [comment]
are you getting the invalid utility message for `bg-black` or for `text-primary`?

**Comment by JJK801** [comment]
@adnan-SM Your problem is just you swapped theme and extend key (extend goes inside of theme)

**Comment by jaredh159** [comment]
ah, yes, i didn't see that, thanks @JJK801. that should be the issue here.
