### ISSUE TITLE
is "grow" and "shrink" supported?

### ISSUE THREAD

**Issue by lookis** [jaredh159/tailwind-react-native-classnames#139]
It seems these two class name not supported..

https://tailwindcss.com/docs/flex-grow
https://tailwindcss.com/docs/flex-shrink

**Comment by jaredh159** [comment]
yeah, you're basically correct. they _are_ supported in their **longer form** `flex-grow`, `flex-shrink`, `flex-grow-0`, etc.  But not in just `grow` and `shrink`.  I think tailwind v3 switched to the new shorter versions.  You can use the longer versions now, and the next time I set aside some time to work on this library, I'll add support for the shorter variants.  Or, you're welcome to open a PR as well.

**Comment by lookis** [comment]
@jaredh159 submit a PR, please have a review
