### ISSUE TITLE
Limitation for Objects and "-" in Color configurations

### ISSUE THREAD

**Issue by sondreluc** [jaredh159/tailwind-react-native-classnames#144]
Hi!
I have been trying to reuse a Tailwind configuration from a web project with TWRNC, but I think I've found a bug or limitation in this package when it comes to nested objects and `-` in color names configurations.
The following minimal snippet of configuration works with regular Tailwind, but does not seem to work with TWRNC:
```javascript
module.exports = {
  theme: {
    backgroundColor: {
      neutral: {
        DEFAULT:"#ffffff",
        disabled: "#dce5e8",
        variant: "#f3f5f6",
        "variant-2": "#dce5e8",
      },
      primary: {
        DEFAULT: "#1eafaa",
        subdued: {
          DEFAULT: "#ebf5f5",
          active: "#86d9d6",
         }
      }
    }
  }
}
```

Trying this configuration in TWRNC, I'm not able to reference the background colors `bg-neutral-variant-2` or the `bg-primary-subdued*` classes.
``` tw`bg-neutral-variant-2` ``` returns the value for `bg-neutral-variant`, and ```tw`bg-primary-subdued` ``` and ```tw`bg-primary-subdued-active` ``` returns the entire object for `bg-primary-subdued` `{DEFAULT: "#ebf5f5", active: "#86d9d6"}`
 The classes for the other background colors works. These all work with regular Tailwind, and with the Tailwind CSS Intellisense extention for VSCode. 

So my question is: Is this a bug, or just a deliberate implementation, and is there any plan for fixing or extending the support?
If it's done deliberately, what is rational behind it? I may be able to provide some contribution for the support, but I would first like to know if there is any known pitfalls or blockers for it.

**Comment by sondreluc** [comment]
Thanks for such a quick reply. 

That's understandable. Im not sure if Tailwind has a limit, but some sort of depth limit does sounds reasonable,
I might try to give it a shot, but it might take me some time, as my spare time is a bit limited at the moment.
Thanks for pointing me in the right direction!

**Comment by sondreluc** [comment]
[jaredh159](https://github.com/jaredh159) I've made an attempt at it in #150

**Comment by jaredh159** [comment]
@sondreluc just gave it a fairly brief skim, but looks really good.  i'll try to dig in and really kick the tires before long. thanks for the contribution!
