### ISSUE TITLE
Image tintColor support ?

### ISSUE THREAD

**Issue by lucienbl** [jaredh159/tailwind-react-native-classnames#148]
Hello,

First of all, I'd like to thank you for this awesome package!
I discovered it recently so I'm pretty new to it and I'm now using it in a new project, but I can't find any way to use `tintColor` on images using the tailwind syntax. Is this feature not supported or did I just miss something ? 

Thanks in advance for your response :)

Best regards,
Lucien

**Comment by jaredh159** [comment]
@lucienbl the goal of the library is to support all of the tailwind utilities that directly map to a RN (native, not web) style prop. So in the case of `tintColor`, it's supported in RN native, but it has no counterpart in tailwindcss (that I'm aware of). 

that said, we've implemented a few RN-only utilities, so I'm not opposed to adding this functionality, if you're interested in working on the feature.

**Comment by lucienbl** [comment]
@jaredh159 thank you very much for your quick reply. I'll have a look to integrate this feature then :)

**Comment by lucienbl** [comment]
@jaredh159 I opened a PR (#149) with `tintColor` support, let me know if I forgot something.

**Comment by jaredh159** [comment]
closed by #149.
