### ISSUE TITLE
Add support for position absolute and relative

### ISSUE THREAD

**Issue by PedroSSM2000** [jaredh159/tailwind-react-native-classnames#152]
Styling components with position utility classes do not return anything. For example: styling tw`absolute` does not return { position: "absolute" } and nor does tw`relative`. IIRC React Native doesn't support any other positions. Thanks for the library!

**Comment by jaredh159** [comment]
they are supported, see:

https://github.com/jaredh159/tailwind-react-native-classnames/blob/master/src/styles.ts#L54-L55

and test cases validating they work here: 

https://github.com/jaredh159/tailwind-react-native-classnames/blob/master/src/__tests__/simple-mappings.spec.ts#L47-L48

are you sure there's not something else going on?

**Comment by PedroSSM2000** [comment]
Sorry for opening the issue without looking more into the docs, I was using a media query with absolute on react-native web and it didn't seem to appear ever. I was not aware that screen-size breakpoints require the useDeviceContext hook. Again, thanks for the library!

**Comment by jaredh159** [comment]
No worries, glad you figured it out.
