### ISSUE TITLE
borderLeftRadius, borderRightRadius aren't styles

### ISSUE THREAD

**Issue by finnmerlett** [jaredh159/tailwind-react-native-classnames#157]
Opened a new issue to track this so that it doesn't get lost. Feel free to close this issue if the other one is re-opened.

https://github.com/jaredh159/tailwind-react-native-classnames/issues/95#issuecomment-1118081458

**Comment by finnmerlett** [comment]
The following code to be added above [this line](https://github.com/jaredh159/tailwind-react-native-classnames/blob/76e3e8ea00b4cb6b9af2f490193ad0507c52a5d8/src/resolve/borders.ts#L107). I am currently using a `patch-package` patch to fix this, happy to provide a copy of the patch file if anyone needs it in the meantime.

```javascript
    const left = ir.style.borderLeftRadius;
    if (left !== undefined) {
        ir.style.borderBottomLeftRadius = left;
        ir.style.borderTopLeftRadius = left;
        delete ir.style.borderLeftRadius;
    }
    const right = ir.style.borderRightRadius;
    if (right !== undefined) {
        ir.style.borderBottomRightRadius = right;
        ir.style.borderTopRightRadius = right;
        delete ir.style.borderRightRadius;
    }
```

**Comment by jaredh159** [comment]
@finnmerlett thanks for bringing this to my attention. would you mind taking a look at #158 to see if it looks correct to you?
