### ISSUE TITLE
Customize default styles

### ISSUE THREAD

**Issue by JamesHemery** [jaredh159/tailwind-react-native-classnames#159]
Hi @jaredh159,

Thank you for your work.

I wanted to know if you would be open to the possibility of customizing defaultStyles? For example, on our side we don't want to have the classes font-100, font-thin, ..., font-900, font-black.

Because in our tailwind config, we decided to have fonts named medium, bold, ... and to directly use font-bold to define the font-family instead of defining the font-weight. 

Thank you in advance,

**Comment by jaredh159** [comment]
I'm not 100% clear on why you want to customize the default styles. You can define your own custom utilities if you want, and you don't need to use the pre-defined utilities if they're not useful to you.

Is there some way that I'm not thinking about that the default styles are causing you a problem? Or are you just concerned about the performance implications about unused defaults?

**Comment by JamesHemery** [comment]
@jaredh159 It seems that the default values are directly resolved injected in the cache, so it is not possible to override them. I can provide you with an example repo if you want.

**Comment by JamesHemery** [comment]
@jaredh159 A quick example:

I add a font to my tailwind config:

```
module.exports = {
    theme: {
        fontWeight: {},
        fontFamily: {
            'medium': ['Gotham-Medium']
        },
    }
}
```

This has the effect of declaring a tailwind font-medium class. However, in the defaultStyles there is already a font-medium class, which is directly resolved and injected into the cache so my class is not taken into account.

**Comment by jaredh159** [comment]
ah, got it, that's helpful. that seems like a bug, might not be too hard to fix, i'll try to take a crack fairly soon.

**Comment by natemartins** [comment]
@JamesHemery Please do you mind sharing the patch? Thanks

**Comment by JamesHemery** [comment]
> @JamesHemery Please do you mind sharing the patch? Thanks

Just remove the default styles that bother you in the `node_modules/twrnc/dist/cjs/styles.js` file, and patch with patch-package.

Ex: https://gist.github.com/JamesHemery/8d46593f0b9f4957609121f20ce3c608

**Comment by natemartins** [comment]
> 

Alright. Thanks man
