### ISSUE TITLE
Customizing Breakpoints not working v3

### ISSUE THREAD

**Issue by Aris-ngoy** [jaredh159/tailwind-react-native-classnames#163]
module.exports = {
  //mode : 'jit',
  theme: {
    screens: {
      xs: '320px',
      sm: '380px',
      md: '420px',
      lg: '680px',
      // or maybe name them after devices for `tablet:flex-row`
      tablet: '1024px',
    },
    fontFamily :{
      'sans' : ['DMSans-Regular'],
      'display' : ['DMSans-Bold'],
      'body' : ['DMSans-Regular'],
      'medium' : ['DMSans-Medium']
    },
    extend: {
      screens: {
        xs: '320px',
        sm: '380px',
        md: '420px',
        lg: '680px',
        // or maybe name them after devices for `tablet:flex-row`
        tablet: '1024px',
      },
      colors : {
        primary: {
          '100': "#E5E1FD",
          '200': "#CBC4FC",
          '300': "#ADA4F6",
          '400': "#958BEE",
          '500': "#7165E3",
          '600': "#5449C3",
          '700': "#3B32A3",
          '800': "#262083",
          '900': "#18136C",     
        },
        'app_light_gray' : "#F5F5FB",
        'bold-text-color' : '#1C1939',
        'vivid-orange' : '#E26509',
        'page' : '#f9f9fb',
        'app_gray' : "#9EA6BE",
        'new_primary' : '#1C1939',
      }
    }
  },
  variants: {},
  plugins: []
}

this is my tailwind.config

//style
<Text style={tailwind.style('xs:text-[10px]')}>Welcome</Text>

**Comment by jaredh159** [comment]
Did you follow the section of the readme that describes how to enable these prefixes? 

https://github.com/jaredh159/tailwind-react-native-classnames#enabling-device-context-prefixes

Also be sure you read the section on "customizing", and that you're using your own customized version of the `tw` function.
