### ISSUE TITLE
`rounded` produces unwanted gradient artifact when the app is swiped up

### ISSUE THREAD

**Issue by Nova41** [jaredh159/tailwind-react-native-classnames#164]
Hi!

I have been playing with the `rounded` classname and noticed it produces some gradient artifact when the app is swiped up / being moved to the background, as can be seen in the video:

https://user-images.githubusercontent.com/19856332/171766295-0fa749a3-c8d1-4d51-ad82-9a4a0fcd1cb0.mp4

However `rounded-md` and `rounded-lg` do not seem to have this issue.

Code for reproduction:

```
const App = () => {
  return (
    <View style={tw`flex-1 bg-white items-center justify-center p-2`}>
      <Text style={tw`font-semibold m-2`}>rounded</Text>
      <View style={tw`rounded p-2 bg-white border-l-4 shadow-md`}>
        <Text style={tw`text-3.2 font-semibold mb-0.5`}>Title</Text>
        <Text style={tw`text-3.2 mb-0.5`}>This is the description section of this item.</Text>
        <Text style={tw`text-3.2 text-gray-400`}>time</Text>
      </View>
      <Text style={tw`font-semibold m-2`}>rounded-md</Text>
      <View style={tw`rounded-md p-2 bg-white border-l-4 shadow-md`}>
        <Text style={tw`text-3.2 font-semibold mb-0.5`}>Title</Text>
        <Text style={tw`text-3.2 mb-0.5`}>This is the description section of this item.</Text>
        <Text style={tw`text-3.2 text-gray-400`}>time</Text>
      </View>
    </View>
  )
}
```

Environment:
- React Native: `0.68.2`
- twrnc: `3.3.2`
- Simulator: `iOS 15.4 - iPhone 13`

**Comment by Nova41** [comment]
Update: upon further investigation, this only seems to happen when only one side of the border is shown e.g. with `border-l` or `border-r`.

Also, the issue goes away if a JIT value higher than 1.1 is used e.g. `rounded-1.2`

**Comment by jaredh159** [comment]
do you have any reason to believe this issue is directly related to _this_ library? it seems like this is likely just a RN issue, since all this library does is translate tailwind-style utility classes to RN style objects.  can you reproduce the same issue just with raw style objects or stylesheets?

**Comment by Nova41** [comment]
It seems this is an RN issue as I can produce the same result with stylesheets.

I am closing this issue as it is not related to this library.

Thank you for such an awesome library!
