### ISSUE TITLE
Add arbitary values for border(top|right|bottom|left)

### ISSUE THREAD

**Issue by dez64ru** [jaredh159/tailwind-react-native-classnames#166]
Whould be good set like this ``` tw`border-b-[5px]` ```

**Comment by jaredh159** [comment]
yeah, agreed, this would be nice. next time i do a serious chunk of work on this library, I'll try to add support, or this would be a good first issue for a contributor to tackle. thanks for the issue.

**Comment by Karthik-B-06** [comment]
@jaredh159 This issue can be closed as it is been fixed in the latest version 🎉
