### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by lavablelavs** [jaredh159/tailwind-react-native-classnames#172]
I can't seem to get darkMode to work with twrnc
![IMG_3620](https://user-images.githubusercontent.com/64797361/177051372-3700b4b7-0193-4679-83f6-48981ad54c4b.PNG)
<img width="549" alt="Screen Shot 2022-07-04 at 12 47 33 AM" src="https://user-images.githubusercontent.com/64797361/177051382-2878b678-bfec-4979-9840-b0f8e6784fe4.png">

```tsx
<SafeAreaView style={tw`flex-1 bg-[#3B63FB] dark:bg-yellow-200`}>
```

**Comment by jaredh159** [comment]
this is usually caused by a failure to properly configure `tw` with device context.  did you follow the steps in this section of the readme?

https://github.com/jaredh159/tailwind-react-native-classnames#enabling-device-context-prefixes

**Comment by lavablelavs** [comment]
Seems like its still not working, im using this in expo btw
