### ISSUE TITLE
Can't using spacing utilities

### ISSUE THREAD

**Issue by henrychea** [jaredh159/tailwind-react-native-classnames#173]
```<View style={tw`flex flex-col space-x-2`}>```

Results in 

<img width="362" alt="Screen Shot 2022-07-06 at 15 55 10" src="https://user-images.githubusercontent.com/40254517/177511696-c4a1942a-85ff-456f-9328-49e1930a4a1c.png">

**Comment by jaredh159** [comment]
that's because this library only implements tailwind utilities that have a direct counterpart in RN Native styles.  There's no way to use sibling/adjacent combinators in RN native styles, so `space-x-2` can't be implemented.

**Comment by henrychea** [comment]
Thanks for the info!
