### ISSUE TITLE
Text Base and Tracking Tight

### ISSUE THREAD

**Issue by Sydney-o9** [jaredh159/tailwind-react-native-classnames#176]
It seems `tracking-tight` doesn't play well with `text-base`, however simply overiding it to its default which is 1rem (`text-[1rem] ` does fix it.

```
<Text style={styles.buttonText} numberOfLines={1}>{'Continue with Google'}</Text>
```

```
const styles = {
  buttonText: tw`font-bold text-base tracking-tight`,
};
```

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1480617/179519538-ef155c57-6ee0-4a3b-b186-04afb512fe23.png">

```
const styles = {
  buttonText: tw`font-bold text-[1rem] tracking-tight`,
};
```

<img width="1584" alt="image" src="https://user-images.githubusercontent.com/1480617/179519321-8fdc57ed-651c-40dd-96a0-2a9ea15e4b16.png">

**Comment by jaredh159** [comment]
this might be because `text-base` generates styles for both `fontSize` _and_ `lineHeight` (following Tailwindcss), so your first example is sort of specifying line-height _twice_.  When you switch to an arbitrary value for font size (`text-[1rem]`) you don't get any built-in line height.

**Comment by jaredh159** [comment]
closing for now. if you have more info, feel free to re-open. 👍
