### ISSUE TITLE
Capitalize doesn't work as expected

### ISSUE THREAD

**Issue by akinncar** [jaredh159/tailwind-react-native-classnames#177]
Doesn't work:
```js
<Text style={tw`text-white capitalize`}>Hello</Text>
```

Work with a warning:
```js
<Text style={tw`text-white captalize`}>Hello</Text>
```
<img width="382" alt="image" src="https://user-images.githubusercontent.com/42688281/179642883-01066606-902d-43f8-befb-538b269262a9.png">

**Comment by jaredh159** [comment]
i'm not sure exactly what you're reporting, can you clarify?  in your second example you've got the utility misspelled, it should be `capitalize`, not `captalize`.

the first example should work.  are you saying that the misspelled version _was working?_

**Comment by akinncar** [comment]
yes, `capitalize` doesn't capitalize the text, `captalize` capitalize the text but shows a warning
I'm using:
```js
"twrnc": "^3.3.3",
"react-native": "0.69.1",
```

**Comment by jaredh159** [comment]
yeah, i searched the whole repo for `captalize` and it's not in there. it's likely there's something else going on in your code that is causing it to appear to work.  text components in RN do sort of "cascade", so can you check if some text element parent perhaps has the styling set?
