### ISSUE TITLE
[proposal] shadow-offset-x-[foo] and shadow-offset-y-[bar]

### ISSUE THREAD

**Issue by jbtheard** [jaredh159/tailwind-react-native-classnames#178]
Currently, `shadow-offset-[foo]` will set both _width_ and _height_ of the RN property `shadowOffset` to `foo`.
Ideally we would be able to specify width/eight independently. if one is missing assume it's zero

**Comment by jaredh159** [comment]
you are correct, but there is also a syntax for controlling each dimension, using the `/`, so `shadow-offset-[foo]/[bar]` will set the width to `foo` and the height to `bar`. it is documented in the readme, but perhaps it could be made more clear.

**Comment by jaredh159** [comment]
are you proposing that we add an additional variant for controlling _just one_ dimension? if so, i would probably be open to that, if the slash syntax doesn't cover the use case.  probably something like `shadow-offset-w-X` or `shadow-offset-h-X`.

**Comment by jaredh159** [comment]
i lean slightly more towards `-w-X` and `-h-X` because it seems a bit more consistent with other utilities and tailwind's naming convention.

**Comment by jbtheard** [comment]
Oh I actually missed that though well documented! Sorry for that. 
My use case is indeed to focus on a single dimension but using `shadow-offset-0/X` does actually work as expected.
Case solved.

If you were to change that, I reckon `shadow-offset-w-X` / `shadow-offset-h-Y` could be a better fit

**Comment by jaredh159** [comment]
ok good deal, i think i'll close this then. if you (or someone else) feels motivated to implement the individual variations, i'd be open to merging a PR, but i'm guessing it's not terribly pressing. 👍
