### ISSUE TITLE
Is it possible to use this package outside of a React Native project?

### ISSUE THREAD

**Issue by sandren** [jaredh159/tailwind-react-native-classnames#18]
There are things like [React PDF](https://react-pdf.org/) that use the same layout engine as React Native and it would be great to be able to use `tw` to style PDF documents! 😀

**Comment by jaredh159** [comment]
I'm not sure if that would be possible.  If it had an API that accepted RN-like style objects (which is what the functions in this package produce), then it would likely work.  Give it a shot and let me know if you encounter anything. 👍
