### ISSUE TITLE
Custom colors not working

### ISSUE THREAD

**Issue by JosephKorel** [jaredh159/tailwind-react-native-classnames#183]
Hi, i added colors to the tailwind.config.json file, but it says that the color 'myColor' doesn't exist. I'm adding it as this

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        persian: {
          DEFAULT: "#F72585",
          50: "#FDD6E8",
          100: "#FDC2DD",
          200: "#FB9BC7",
          300: "#FA74B1",
          400: "#F84C9B",
          500: "#F72585",
          600: "#DC0869",
          700: "#A6064F",
          800: "#700435",
          900: "#39021B",
        },
```

**Comment by jaredh159** [comment]
where is the name `myColor` coming from?  is that in the warning?  how are you trying to use these at the call site?  if you do something like: 

```ts
tw`bg-persian-300`
```

it should work.

that said, a common mistake is to forget to actually use a _configured, customized_ version of the `tw` function, which takes another step, as shown here: https://github.com/jaredh159/tailwind-react-native-classnames#customization -- double check that you're actually using your tailwind config in that manner.

**Comment by JosephKorel** [comment]
I completely missed that! Now it's working perfectly, thank you very much
