### ISSUE TITLE
I'm getting this console warning when I try to use template literals with tw styling in react native.

### ISSUE THREAD

**Issue by Ademie** [jaredh159/tailwind-react-native-classnames#184]
`false` unknown or invalid utility
at node_modules/twrnc/dist/cjs/helpers.js:190:4 in consoleWarn
at node_modules/twrnc/dist/cjs/ClassParser.js:324:8 in parseUtility
at node_modules/twrnc/dist/cjs/ClassParser.js:111:19 in parse
at node_modules/twrnc/dist/cjs/create.js:73:22 in style
at components/RideCard.js:48:15 in FlatList.props.renderItem
at node_modules/react-native/Libraries/Lists/FlatList.js:597:25 in renderer
at node_modules/react-native/Libraries/Lists/FlatList.js:629:25 in virtualizedListRenderKey
at node_modules/react-native/Libraries/Lists/VirtualizedList.js:2008:23 in CellRenderer#_renderElement
at node_modules/react-native/Libraries/Lists/VirtualizedList.js:2033:20 in CellRenderer#render

This is an example code: 

  <TouchableOpacity onPress={()=>setSelected(item)}
        style={[tw`flex-row items-center justify-between px-10 ${id === selected?.id && "bg-gray-200"}`]}>
   </TouchableOpacity>

**Comment by Ademie** [comment]
Found out that this issue is with the new "twrnc" package so I installed the previous version "tailwind-react-native-classnames"

So I am using both packages and I don't now if it can pose a threat to my app in the future kindly resolve this issue.

**Comment by jaredh159** [comment]
The correct way to express what you're trying to do is by using `tw.style(...)` like so:

```tsx
<SomeComponent style={tw.style("flex-row items-center justify-between px-10", id === selected?.id && "bg-gray-200")} />
```

The way you're writing it currently is producing a string `false` which is an invalid tailwind utility. If you need logic to be executed to select a utility, use `tw.style()` it will reject falsy values.

**Comment by jaredh159** [comment]
You should _not_ be using the old NPM name, that will just install a much older version of the library.
