### ISSUE TITLE
Using breakpoint on height

### ISSUE THREAD

**Issue by AChevallier** [jaredh159/tailwind-react-native-classnames#188]
Hello there !

I would like to use breakpoint on the height but I couldn't make it work.

The breakpoint with the width is working well.

I was following this : https://tailwindcss.com/docs/screens#custom-media-queries

Can you help me to know how to solve my problem ? 

Thank you very much !

**Comment by jaredh159** [comment]
i'm not 100% sure how to help you without spending some time thinking about it, i haven't worked on this part of the library very recently, but i was just looking through the tests, and it seems like one thing you could do is take advantage of the fact that it should correctly support arbitrary min-height breakpoint prefixes, like : `min-h-[600px]:text-lg` -- there are tests in the test suite proving that those types of utitlities work.

would that solve your use case?

**Comment by AChevallier** [comment]
I guess I will mix your solution and create a tailwind plugin to solve my problem ! 

Thank you @jaredh159
