### ISSUE TITLE
How to referencing theme config in JavaScript?

### ISSUE THREAD

**Issue by thanhloc-17** [jaredh159/tailwind-react-native-classnames#189]
Hi @jaredh159,

Thank you for your work.

What should I do if I want to use Resolved TailwindConfig in my .js file?

Readmor: https://tailwindcss.com/docs/configuration#referencing-in-java-script

Thank you.

**Comment by jaredh159** [comment]
I think you should be able to do exactly like that code sample on the tailwind docs site. Did you try it? Was it not working for you?

Internally we call `resolveConfig()` as well, but we don't expose the merged configuration.  But there shouldn't be any problem calling it on your own somewhere and getting a reference to the merged config and then using it.  But that said, I've not tried this with a RN app and twrnc, so there may be something I'm not thinking of.

**Comment by jaredh159** [comment]
feel free to re-open with additional information, closing for now since I haven't heard back.
