### ISSUE TITLE
breakpoint styles not working.

### ISSUE THREAD

**Issue by shellord** [jaredh159/tailwind-react-native-classnames#190]
Styles like <View style={tw`xs:bg-black`} /> not working.

my tailwind.config.js

import theme from './src/styles/theme.ts';

module.exports = {
  theme: {
    screens: {
      xs: '50px',
      sm: '380px',
      md: '420px',
      lg: '680px',
      tablet: '1024px',
    },
    extend: {
      backgroundColor: {
        primary: theme.COLORS.PRIMARY,
        secondary: theme.COLORS.SECONDARY,
      },
    },
  },
};

**Comment by jaredh159** [comment]
this is most often caused by failure to connect the `tw` function to the source of _runtime device information_ as described in the readme here:

https://github.com/jaredh159/tailwind-react-native-classnames#enabling-device-context-prefixes

Did you do that step?

**Comment by shellord** [comment]
Thanks. I missed that step. Working fine now.
