### ISSUE TITLE
Intellisense support for custom utilities

### ISSUE THREAD

**Issue by sbycrosz** [jaredh159/tailwind-react-native-classnames#192]
Hi, 

Is there a way to enable IntelliSense autocompletion support when using custom utility classes?

Cheers, 
Sam

**Comment by sbycrosz** [comment]
Just found that when we have `.` on the class name, IntelliSense will [work as expected](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/227#issuecomment-1139895799)

So [this solution](https://gist.github.com/sbycrosz/5afa805e8198ed60fbe0009b4088aebf) kind of work, but do you by any chance have a better solution?

Cheers, 
Sam

**Comment by jaredh159** [comment]
it's not something i've looked into, so i can't really help.  you may find some additional info on the discussion thread we have going about intellisense, and maybe you could (re) post your question/findings over there as well. i'm going to close this issue and you can continue over there.  👍

https://github.com/jaredh159/tailwind-react-native-classnames/discussions/124
