### ISSUE TITLE
Feature request: Could you please add support for IntelliSense for autocomplete in twrnc?

### ISSUE THREAD

**Issue by AnatuGreen** [jaredh159/tailwind-react-native-classnames#193]
Feature request: Could you please add support for IntelliSense for autocomplete in twrnc?
This will be well appreciated.
So stressful having to type everything.

**Comment by jaredh159** [comment]
that's an editor feature, not something in the scope of this library. 

see this discussion for help:

https://github.com/jaredh159/tailwind-react-native-classnames/discussions/124

**Comment by AnatuGreen** [comment]
Thanks. I found an easier solution even: [Here](https://stackoverflow.com/a/73977534/14600144)
