### ISSUE TITLE
basis (flexBasis) not implemented?

### ISSUE THREAD

**Issue by rborn** [jaredh159/tailwind-react-native-classnames#202]
Hey, first of all thanks a lot for this library, it is amazing 🙏 

It looks to me that `basis` is not implemented, I need to do 
` <View style={tw.style(`grow-1 p-2 bg-cyan-100 h-10`,{flexBasis:160})}></View>` to work. Am I doing something wrong?

Thank you 🤗

**Comment by jaredh159** [comment]
i think at the time i originally built this library that tailwindcss didn't support flex-basis utilities, but it seems they do now. you're right, it's not currently implemented. so they way you did it is correct.

i'd be happy to look at a PR if you had any desire to implement it yourself.

**Comment by rborn** [comment]
ok,I will try 😻

**Comment by rborn** [comment]
I've made a PR, please have a look because I'm not sure the approach is the correct one 😅

Also the test might fail, but is independent on this, tailwind plugin won't accept numbers in addUtilities

**Comment by jaredh159** [comment]
closed by https://github.com/jaredh159/tailwind-react-native-classnames/pull/204
