### ISSUE TITLE
installation error with Ionic

### ISSUE THREAD

**Issue by andreiwow2** [jaredh159/tailwind-react-native-classnames#203]
Installed using `yarn add twrnc` and when I try to build I get the following:

```
Failed to compile.

Module not found: Error: Can't resolve 'react-native' in '/Users/andrei/KareApp/node_modules/twrnc/dist/esm
```

I have a fresh installation of Ionic with React Native.

**Comment by jaredh159** [comment]
`react-native` is a peer dependency.  do you have it installed?

**Comment by andreiwow2** [comment]
I thought ionic already installed that.

I did `yarn add react-native` and now I have `"react-native": "^0.70.6",` but I still get the same error when I try to build.

**Comment by andreiwow2** [comment]
Apparently it presents itself as an UI Toolkit and works with some frameworks such as angular, react, vue etc

https://ionicframework.com/


I thought it builds on React Native but I think Ionic does not use React Native at all, I think it uses only React and builds the app into a WebView, I think this won't work, sorry for bothering.



I might be able to do the normal install of tailwind since its like a browser

**Comment by jaredh159** [comment]
ok, no problem. best of luck 👍
