### ISSUE TITLE
Error: Cannot find module 'tailwindcss' Require stack

### ISSUE THREAD

**Issue by rachmadideni** [jaredh159/tailwind-react-native-classnames#21]
Hi Thank you for this great library. any guidance for this ?

![image](https://user-images.githubusercontent.com/3959672/126768710-16560683-ba66-4597-b792-752335dad893.png)

Thank You

**Comment by jaredh159** [comment]
`tailwindcss` is a dev dependency of the library, so it should be installed, because the styles json gets generated during _development_.  Did you possibly install your dependencies using `npm install --only=prod` or `npm install --only=production`?

**Comment by ElektrikSpark** [comment]
I am getting this error too.  I just did `npm install tailwind-react-native-classnames`, but I do not see tailwindcss when I look in my node_modules.  For now I just duplicated the tw-rn-styles.json in the tailwind-react-native-classnames node_module and put that in my project.

**Comment by jaredh159** [comment]
@ElektrikSpark thanks for letting me know, maybe there's something here after all. I'm going to re-open and see if I can replicate. Maybe I need to stipulate that tailwindcss is a peerDependency.  I'm guessing you can temporarily fix it by doing `npm i tailwindcss -D`

**Comment by jaredh159** [comment]
@ElektrikSpark @rachmadideni -- fixed in `1.4.2`. Sorry about that!

**Comment by ElektrikSpark** [comment]
Awesome! Thanks!
