### ISSUE TITLE
Performance improvement idea

### ISSUE THREAD

**Issue by MetinArslanturk** [jaredh159/tailwind-react-native-classnames#22]
Hello, Firstly great approach and library. It is pleasure to use it.
I have an idea as a future improvement.
As i examined the source code, you are parsing class names in every call. In every call it does checks like "isSupportedFontVariant(className)", "isBoxShadowClass(className)" etc. Maybe in every render of that view. This can be expensive at runtime for every style creation.

Do you think a babel plugin for build time conversion can be a good fit? I mean a babel plugin(function) which it visits all files in build time, searches for tw() calls. When it found, it replaces all tailwind classnames with correct inline styles.
I mean your file has got :
`tw.style('bg-blue-100', { elevation: 3, lineHeight: 13.5 });`
it triggers tw.style function in build time and replaces it with:
`[{backgroundColor: 'rgba(219, 234, 254, 1)' }, { elevation: 3, lineHeight: 13.5 }]`
or better it finalizes it to a single object
`{backgroundColor: 'rgba(219, 234, 254, 1)', elevation: 3, lineHeight: 13.5 }`

So, this will happen in build time. Now we have all styles in inline-object. Same plugin can also remove tw imports. No need for it anymore after build. Also the final bundle will not include style.json, it will reduce build file size a little probably. It will be much faster at runtime i think.
I can help with PRs but i wanted to discuss first.
Cheers,
Metin

**Comment by jaredh159** [comment]
Hey, thanks for opening the issue! Yeah, overall, I think this is probably a very good idea, I've had similar thoughts myself.

That said, I wonder if you've done any actual measurement of the potential perf issue.  Are we _sure_ this is causing a problem?  Are you noticing lagginess you can trace to this library?  I would hate to bring in a bunch of complexity for something that we just suppose is a perf issue.  I have an app in production with some really long virtualized lists, all of which use this library, and it performs great.

That's not to say that there isn't a performance issue, it makes intuitive sense to me that I'm wasting a bunch of cycles by recomputing these styles on each re-render.  I'd just like to verify that somehow, if possible.  You have any thoughts on how to actually measure this?

The other thought I had is I wonder if something simple, like a crude memoization wouldn't get us 90% there for less effort.

All that said, I still think it's a really good idea. I like the elegance of the library erasing itself and just leaving behind RN style objects.  I guess I'm pretty open to it, if you're interested in working something up.  I'd want some really good test coverage on the babel AST transformations though.

**Comment by jaredh159** [comment]
Hey, I don't know why I didn't think of this before, but we can't strictly erase the library leaving behind RN style objects, because often the utility classes are applied conditionally, based on props or state, like so:

```tsx
<View style={tw.style("mr-2", !isValid && "text-red-500")}>
```

So maybe a babel plugin could optimize away any declarations that don't contain conditional logic, but for the rest, the library would either need to be there at runtime, or the babel plugin would have to replicate the logic, which sounds a bit hairy.

**Comment by leggomuhgreggo** [comment]
I think you could extract the conditional styles into object references too. Here's how the [pulsar library](https://github.com/elforastero/pulsar-core#how-is-it-different ) generates conditional:
```
// {
//   'button': {},
//   '_var:variant:primary:button': {},
//   '_var:variant:secondary:button': {},
//   '_media:max-width:768:button': {},
// }
```
Things like animations would still need to be inline, of course






https://github.com/necolas/react-native-web/discussions/1801

**Comment by jaredh159** [comment]
Closing, because I'm fairly deep into a v2 rewrite that includes some aggressive internal caching.  This idea may not be necessary when that version lands, or if it still seems useful to have a babel plugin to pre-resolve non-conditional cases at build time than I'll reconsider, and/or re-open this.  Thanks for the input!
