### ISSUE TITLE
Use for react web

### ISSUE THREAD

**Issue by zvitek** [jaredh159/tailwind-react-native-classnames#221]
Hi, I am using NX monorepo and I am writing a mobile app for react native and also for react web using React Native Web.

Unfortunately when I start the web app I get an error in the browser 

```
Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 95075
```

Is it possible to use your implementation also for the web part?

Thank you!

**Comment by jaredh159** [comment]
are you sure that error is coming from `twrnc`?  I'm not aware of any reason why you'd get an error with nx and a monorepo, but there are tons of configuration issues that could be at play. 

as far as RN Web goes, it's not an aim of this library to support web utilities, see here for more context: 

https://github.com/jaredh159/tailwind-react-native-classnames/discussions/125
