### ISSUE TITLE
Wrong limits for breakpoints?

### ISSUE THREAD

**Issue by rborn** [jaredh159/tailwind-react-native-classnames#223]
I think the breakpoints are calculated wrong? 
My understanding is that they should include the min value in the "next" range and not exclude it? 

Eg: 

`breakpoint:1024px` will  consider **before** breakpoint if  `width <= 1024` but it should be `width < 1024`

**Comment by jaredh159** [comment]
hmmm... yeah, maybe we're doing it wrong. are you sure you're clear on how tailwind utils handle these? i think we'd want to carefully match their default behavior.  if you can verify that we're not matching the correct behavior, then yeah, i'd definitely be open to a PR.  ...although it makes me sort of wonder if it should be considered a breaking change, in case anyone's apps are relying on the old behavior 😬

**Comment by rborn** [comment]
I tested with their playground resizing the screen and it does it as I say 😁 
The screens are basically media queries which use `min-width: 576px`. 

I will prepare a PR and maybe we increase to v4 🤣
