### ISSUE TITLE
Possible to use Tailwind Forms?

### ISSUE THREAD

**Issue by KDederichs** [jaredh159/tailwind-react-native-classnames#233]
As the title says, is it somehow possible to get support for tailwind forms? (https://github.com/tailwindlabs/tailwindcss-forms)

**Comment by jaredh159** [comment]
it's not something that i'm planning to do, no, although i might be open to merging a pull request which added some support.

however, from briefly looking at that link, my guess is that it would only really be useful for React Native _Web_ -- as native inputs are pretty different (IIRC) from web forms.

are you targeting RN Web?  the stated goal of this library is only to focus on RN Native.

**Comment by KDederichs** [comment]
No I was trying to style forms on the Native Platforms. Too bad it's not really possible then.
