### ISSUE TITLE
Intellisense is lost as soon as I import anything from twrnc inside the tailwind.config file

### ISSUE THREAD

**Issue by joaocdvr** [jaredh159/tailwind-react-native-classnames#235]
## What
I followed the guide on [VS Code Intellisense](https://github.com/jaredh159/tailwind-react-native-classnames#vs-code-intellisense) and it works perfectly, as long as I don't import anything from `twrnc` inside the `tailwind.config.js` file.

```javascript
// tailwind.config.js
const { plugin } = require("twrnc");

/** @type {import('twrnc').TwConfig} */
module.exports = {
  content: [`**/*.{js,ts,jsx,tsx}`],
  theme: {
    extend: {},
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        test: {
          flex: "1 1 0%",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "white",
        },
      });
    }),
  ],
};
```

This ⬆️ works fine, the `test` class exists and the styles are applied properly, the issue is that I lose intellisense. Even if I comment out the custom plugin function, if I keep the `twrnc` import, intellisence doesn't work.

On the other hand, if I use the `plugin` function from `tailwindcss/plugin`, intellisense works for every class that isn't part of a plugin:
```javascript
// tailwind.config.js
const plugin = require("tailwindcss/plugin");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [`**/*.{js,ts,jsx,tsx}`],
  theme: {
    extend: {},
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        "test": {
          flex: "1 1 0%",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "white",
        },
      });
    }),
  ],
};
```
If I use the "normal" tailwind plugin syntax and write the class as `.test` instead of `test`, I have intelisense in every class (including the `test` class) but the styles aren't applied and I get a `'test' unknown or invalid utility` warning.

Is this a known issue? Is there a workaround?

### Notes

For reference, I have the Tailwind CSS IntelliSense (`bradlc.vscode-tailwindcss`) plugin installed with the following settings:
```json
// .vscode/settings.json
{
  "tailwindCSS.classAttributes": ["style"],
  "tailwindCSS.experimental.classRegex": [
    "tw`([^`]*)",
    ["tw.style\\(([^)]*)\\)", "'([^']*)'"]
  ]
}
```

**Comment by kyimoemin** [comment]
same here

**Comment by kyimoemin** [comment]
I have able to fix it by changing the `config` type of `CreatePlugin` function in twrnc type file

```ts
//node_modules/twrnc/dist/esm/types.d.ts
export declare type CreatePlugin = (pluginFunction: PluginFunction) => {
    handler: PluginFunction;
- config:undefined;
+ config: Partial<ConfigType>;
};
```

**Comment by joaocdvr** [comment]
Hey @jaredh159, in the first example of the issue's description I'm using `twrnc`'s `plugin` function but as soon as I import anything from `twrnc` inside the `tailwind.config.js` file I lose all intellisense unfortunately. I could just use `tailwind`'s `plugin` function but it expects the classes to be prefixed by a `.` for intellisense to work but if I do that I get `'test' unknown or invalid utility` warning in `react-native` and the styles aren't applied. Here's a screen recording that highlights the issue: 

https://github.com/jaredh159/tailwind-react-native-classnames/assets/63152281/b315350e-0e98-49c2-9f39-9a45215dd5b8

I guess ideally I could prefix the classes with a `.` like you do usually with `tailwind` and the styles would be applied 🤔 
Would that be possible? Thanks for looking into this btw 🙏

**Comment by joaocdvr** [comment]
Damn, amazing, it works! Thank you @jaredh159 🙏 
But just so you know, it only works if I import the `tailwindcss/plugin` function, as soon as I import anything from `twrnc` the intellisense is broken

**Comment by joaocdvr** [comment]
Just to be clear, atm the only plugin I can create is a [utility with the addUtilities function](https://github.com/jaredh159/tailwind-react-native-classnames/blob/master/src/plugin.ts), correct?

**Comment by jaredh159** [comment]
> Just to be clear, atm the only plugin I can create is a [utility with the addUtilities function](https://github.com/jaredh159/tailwind-react-native-classnames/blob/master/src/plugin.ts), correct?

yup, that's correct, for now at least. 

thanks for testing, i think i'll merge #236 and cut a non-beta release 👍

**Comment by joaocdvr** [comment]
@jaredh159, just so you know [this](https://github.com/jaredh159/tailwind-react-native-classnames/blob/b0e569cf5b28d954bd1b95233484c81e02646930/readme.md?plain=1#L317-L327) also breaks intellisense, I guess because it's unexpected by the [Tailwind CSS Intelissense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) plugin

**Comment by jaredh159** [comment]
> @jaredh159, just so you know [this](https://github.com/jaredh159/tailwind-react-native-classnames/blob/b0e569cf5b28d954bd1b95233484c81e02646930/readme.md?plain=1#L317-L327) also breaks intellisense, I guess because it's unexpected by the [Tailwind CSS Intelissense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) plugin

ok, thanks for letting me know. not sure there's an easy fix for that. 🙁

**Comment by joaocdvr** [comment]
I think it's a cool feature but [tailwindcss-intellisense](https://github.com/tailwindlabs/tailwindcss-intellisense) would have to support it and I guess that would only happen if `tailwindcss` itself started supporting that syntax as well 🤔
