### ISSUE TITLE
`screen` unknown or invalid utility 

### ISSUE THREAD

**Issue by Siumauricio** [jaredh159/tailwind-react-native-classnames#244]
Hi, first of all thanks for this great library!

I noticed some properties don't work or maybe I'm doing something wrong.

`w-screen`, `h-screen`, `border-none`

and the error is something like this `screen` unknown or invalid utility
also for the border it's `-none` unknown or invalid utility

![image](https://github.com/jaredh159/tailwind-react-native-classnames/assets/47042324/61db6a6c-be4f-4db6-8ec5-bb76b982fba0)

```tsx
import tw from 'twrnc';
```

I tried to remove the border, but nothing works, only works if i use like `border-t-0` and `border-b-0`
```tsx
      <CalendarPicker
        allowRangeSelection
        showDayStragglers
        dayLabelsWrapper={tw`h-screen border-none`} <-- Here
        todayBackgroundColor="#000000"
        selectedDayColor="#000000"
        minDate={moment().add(1, 'day').toDate()}
        selectedDayTextColor="#ffffff"
        allowBackwardRangeSelect
        onDateChange={(date, type) => {
          console.log(type);
        }}
      />
```
      
      
Tailwind config
      
```js
 /** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

**Comment by jaredh159** [comment]
regarding `border-none` -- that utility is not supported, because there is no concept of `"none"` for a border style in RN native, see here:

https://reactnative.dev/docs/view-style-props#borderstyle

but `w-screen` and `h-screen` should work, provided you used the `useDeviceContext()` hook properly, as described in the readme. did you do that?

**Comment by Siumauricio** [comment]
Thanks!, I tought it doesn't was necessary
