### ISSUE TITLE
tailwind version

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#25]
Hey, 

could you update this great tool to the new tailwindcss ?
actually tailwind-react-native-classnames use tailwindcss 2.0.0, the latest is 2.2.6.
Maybe it not needed because native can't use the new features ?

thanks

**Comment by jaredh159** [comment]
the package.json specifies `^2.0.0`, so it installs the very latest version in the `2.x.x` major version.

**Comment by jaredh159** [comment]
Meaning, because of how semver and npm works, it currently installs `2.2.7`, not `2.0.0`.
