### ISSUE TITLE
npx trnc-create-styles error

### ISSUE THREAD

**Issue by fristyr** [jaredh159/tailwind-react-native-classnames#26]
Hi!
I was trying to use customization
But when I tried **npx trnc-create-styles** 

![Screenshot 2021-08-04 205528](https://user-images.githubusercontent.com/33237937/128239184-d274e105-6b23-4f28-97dd-95b8c560f46d.png)

**Comment by jaredh159** [comment]
is your project open source? can you give me the github url so I can look into it? I'd need more info than just the error message.

**Comment by AVivero** [comment]
@fristyr - I think you might solve that issue by installing postcss-cli as a global dep. Make sure the installed version is >= 8.0.

@jaredh159 Great library, it works great!
