### ISSUE TITLE
tailwind intellisense not working

### ISSUE THREAD

**Issue by eugerr** [jaredh159/tailwind-react-native-classnames#268]
![image](https://github.com/jaredh159/tailwind-react-native-classnames/assets/156797561/10d55e79-fb2d-4b3a-b41f-1df91cf7034a)
![image](https://github.com/jaredh159/tailwind-react-native-classnames/assets/156797561/5272952c-9a66-4554-9a9e-697169d57dbb)

It's working fine, but the hitch is that IntelliSense doesn't kick in when I'm coding in React Native, unlike in other file types where it works smoothly.

**Comment by jaredh159** [comment]
check out all the info on setting up intellisense over here:

https://github.com/jaredh159/tailwind-react-native-classnames/discussions/124

and comment on that thread if you're still stuck 👍
