### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#28]
Hey, is this possible to have  responsive design system with tailwind classnames ?
This library in native allow that : https://github.com/nandorojo/dripsy
its possible to do with hooks but its heavy to do for styling system. What do you think ?
thanks

**Comment by electroheadfx** [comment]
I had not chance to test it yet : https://tailwindcss.com/docs/responsive-design
in your doc it talk about platform support only.

**Comment by jaredh159** [comment]
Not currently supported in this version.

I've started work on an v2 re-write of this library, and my plan is for the new version to support a quasi-media query functionality, using `useWindowDimensions` to dynamically generate conditional styles based on current window dimensions. So, possibly in a future version.
