### ISSUE TITLE
Teaches you how to implement automatic syntax prompts in webstorm.

### ISSUE THREAD

**Issue by yangfei4913438** [jaredh159/tailwind-react-native-classnames#282]
webstorm configuration, I hope to help you

1. Check the version. Available for [WebStorm 2023.1(opens in a new tab)](https://www.jetbrains.com/webstorm/whatsnew/#version-2023-1-tailwind-css-configuration) and later
2. Open the settings. Go to [Languages and Frameworks | Style Sheets | Tailwind CSS](https://www.jetbrains.com/help/webstorm/tailwind-css.html#ws_css_tailwind_configuration)
3. Add the following to your tailwind configuration
```js
 "experimental": {
    "configFile": null,
    "classRegex": [
      "tw\\(([^)]*)\\)", "[\"'`]([^\"'`]*).*?[\"'`]"
    ]
  }
```

**Comment by jaredh159** [comment]
hi, thanks for this. i'm going to close this issue, could you post it instead as part of this discussion?

https://github.com/jaredh159/tailwind-react-native-classnames/discussions/124

**Comment by johanpedroo** [comment]
don't works for me :/
