### ISSUE TITLE
`container` utility is not working

### ISSUE THREAD

**Issue by yushanwebdev** [jaredh159/tailwind-react-native-classnames#286]
I'm receiving the following warning from Expo 50:

> container unknown or invalid utility

Is it not supported here?

**Comment by jaredh159** [comment]
we only support the subset of tailwindcss utilities that _directly map_ to React Native non-web style props.  Another way of saying that, is we don't support React-Native Web. So utilities like `container` I believe have no counterpart in pure native RN, so the library doesn't support them.

**Comment by yushanwebdev** [comment]
Ah, okay, @jaredh159. Thank you.
Is there documentation available on the supported Tailwind CSS utilities?
