### ISSUE TITLE
No support for spacing?

### ISSUE THREAD

**Issue by stesvis** [jaredh159/tailwind-react-native-classnames#289]
It appears that there is no support for spacing, for example this throws a warning:
```jsx
<View style={tw`space-y-3`}>
  <Text>First text</Text>
  <Text>Second text</Text>
</View>
```

and the warning is ```WARN  `space-y-3` unknown or invalid utility```

Basically I am looking for these:
https://tailwindcss.com/docs/space

**Comment by stesvis** [comment]
Found that as an alternative I can use `gap-3` and it works.

**Comment by jaredh159** [comment]
glad you figured that out. `space-{dir}-{n}` utilities aren't supported because they only work in a web context, and this library only supports RN native (non-web).
