### ISSUE TITLE
Feature/Bug for Tailwind plugins

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#29]
Do you think its possible to an tailwind ui plugins like daisyui? 
https://daisyui.com/docs/install

I tried to add to tailwind.config.js on plugins and compile it, when I add a button to view i got:
`btn` is not a valid Tailwind class name:
<View style={tw`btn btn-primary`}> ...

thanks

**Comment by electroheadfx** [comment]
hmm sorry I think its not supported because it need JIT, trnc-create-styles compile output:
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.

**Comment by jaredh159** [comment]
yeah, i don't think you'd probably be able to get that to work in RN -- it looks like a good bit of it relies upon CSS cascading and inheritance, which doesn't exist (or work the same where it sort of does) in RN.
