### ISSUE TITLE
How to add custom colors?

### ISSUE THREAD

**Issue by stesvis** [jaredh159/tailwind-react-native-classnames#290]
The goal is to add custom colors as described [here](https://tailwindcss.com/docs/configuration) in the official Tailwind documentation.
```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
     primary: "#f00000",
    },
  },
}
```
but if i do this and use the colors with 
```tsx
style={tw`bg-primary`}
```
I get the runtime error:
> `primary` unknown or invalid utility

even tho the color is recognized:
![image](https://github.com/jaredh159/tailwind-react-native-classnames/assets/6062684/464be276-e350-4aa8-8187-cfe2232c028c)

so far the only solution that seems to work is this:
```tsx
// colors.ts
export const Colors = {
  primary: "#f00000"
};

// MyComponent
import { Colors } from "./colors";

<View style={tw`bg-[${Colors.primary}]`} />
```

Is it possible to leverage the `tailwing.config.js` file instead?

**Comment by codearis** [comment]
I have the same issue

**Comment by jaredh159** [comment]
@codearis can you try moving your color customization into the `"extend":` key and see if that fixes it?

**Comment by codearis** [comment]
> @codearis can you try moving your color customization into the `"extend":` key and see if that fixes it?

Tried, it broke all the colors definitions.

**Comment by jaredh159** [comment]
strange, this is something that tons of users are doing with success, i'm not sure what might be the case with your project. it's not open source is it, so i could look at the code? or could you make a minimal reproduction for me to look at?

**Comment by codearis** [comment]
> strange, this is something that tons of users are doing with success, i'm not sure what might be the case with your project. it's not open source is it, so i could look at the code? or could you make a minimal reproduction for me to look at?

I have an update on this. I was wrongly importing the tw from twrnc instead from my custom theme.

```
- import tw from "twrnc"
+ import { tw } from "@/styles/twrnc";
```

These changes fixed the errors and now I can use custom colors. Thanks for the support @jaredh159
