### ISSUE TITLE
Getting "unknown or invalid utility" for font-size + line-height modifier

### ISSUE THREAD

**Issue by danieltott** [jaredh159/tailwind-react-native-classnames#292]
TailwindCSS [allows us to modify the line-height when using `text-*` line height utilities](https://tailwindcss.com/docs/font-size#setting-the-line-height):

```
className="text-base/6"
```

This should apply the base font size, and the style from `leading-6`.

However setting this via <code>tw`text-base/6`</code> is failing with <code>`base/6` unknown or invalid utility</code>

**Comment by jaredh159** [comment]
yeah, thanks for the issue. the long hand works fine here as a workaround: `text-base leading-6` but you're probably aware of that. i agree that the shorthand should be supported.

made a quick draft PR with a failing test here https://github.com/jaredh159/tailwind-react-native-classnames/pull/293

i'll try to work on an implementation shortly, unless you wanted to take a whack at it.

**Comment by jaredh159** [comment]
implemented in `v4.3.0`
