### ISSUE TITLE
Gradiant background doesn't works

### ISSUE THREAD

**Issue by whtjs** [jaredh159/tailwind-react-native-classnames#294]
Hi first of all, thanks for wonderful library.
I have tried to apply `bg-gradiant-to-r`, but i think parser doesn't parse this function.
Even i look at the code, couldn't find that part.

**Comment by jaredh159** [comment]
we only support the subset of tailwindcss utilities that _directly map_ to React Native non-web style props.  Another way of saying that, is _we don't support React-Native Web._ So utilities like `bg-gradient-{...}` I believe have no counterpart in pure native RN, so the library doesn't support them.
