### ISSUE TITLE
fr: add support for the `web:` prefix.

### ISSUE THREAD

**Issue by achtan** [jaredh159/tailwind-react-native-classnames#301]
Hi, we are using this lib in our monorepo from which we are building rn native apps but also web pages. 

for example when we use the class `self-center` we see warnings that this class is not supported in native. 
We could fix this with `web:self-center` .

**Comment by jaredh159** [comment]
hi, thanks for opening the issue. is the thought here that `web:` would just turn the utility into a no-op with no warning on the native platform?

**Comment by achtan** [comment]
Yes, exactly!

**Comment by aretrace** [comment]
A `web:` prefix would be a great addition for expo/RNW projects.

**Comment by jaredh159** [comment]
yeah, agreed, if anyone wants to PR this, that would be welcome, otherwise I should be able to get to it within a few weeks 👍

**Comment by jaredh159** [comment]
hey there, i went to work on support for this today, and ... I'm pretty sure it **already** works.  see https://github.com/jaredh159/tailwind-react-native-classnames/pull/293/commits/3bcfce31417033215200bc5efc4014af2db997e3

did you actually try something like `web:self-center` or `web:not-valid-nope`? it should not warn you

(on another note: `self-center` is a supported RN native utility as well, you shouldn't have gotten warnings about it)

**Comment by jaredh159** [comment]
ok, well reopen if i'm missing something, but i'm pretty sure this already works, so closing 👍

**Comment by kale5195** [comment]
@jaredh159 doesn't work for web:hover:bg-red-500 ?

**Comment by jaredh159** [comment]
> @jaredh159 doesn't work for web:hover:bg-red-500 ?

`:hover` is not a supported modifier in this library, that's a web only thing.
