### ISSUE TITLE
Custom Box Shadow does not work

### ISSUE THREAD

**Issue by Sydney-o9** [jaredh159/tailwind-react-native-classnames#313]
Hi Team, great work on this library, are custom box shadows supported?

`tailwind.config.js`
```
...
  theme: {
    extend: {
      boxShadow: {
        custom: '0px 1px 20px 0px rgba(0, 0, 0, 0.10)',
      },
    },
  },
...
```

```
<View style={tw`shadow-custom`}
 ...
</View
```

Error:
```
custom unknown or invalid utility
```

**Comment by jaredh159** [comment]
take a second to read the section in the readme about box-shadows -- the web-style string `0px 1px 20px 0px rgba(0, 0, 0, 0.10)` is not going to work here.  it is possible to provide custom shadows, but i would suggest you add a custom utility with the plugin `addUtilities` function, and pass a style object that RN would understand, something like: 

```js
{
      shadowOffset: { width: 1, height: 1 },
      shadowColor: `#000`,
      shadowRadius: 3,
      shadowOpacity: 0.125,
      elevation: 3,
}
```

**Comment by Sydney-o9** [comment]
@jaredh159 Highly appreciate the time in answering to this 👍
