### ISSUE TITLE
Support for Tailwind States

### ISSUE THREAD

**Issue by DavidScicluna** [jaredh159/tailwind-react-native-classnames#319]
Is it possible if you can add support for the [states](https://tailwindcss.com/docs/hover-focus-and-other-states)? This is a must for sure to be able to use this library. Thank you so much for the work you did so far.

**Comment by jaredh159** [comment]
Hi there, thanks for your interest.

This library only aims to support RN _Native_, not RN web, so we only try to support the utilities that exist in a non-web environment. The states you linked to are web-only, which is why they're not supported.
