### ISSUE TITLE
[Question] Supported syntax

### ISSUE THREAD

**Issue by sompol13** [jaredh159/tailwind-react-native-classnames#32]
Hello, Sorry for create an issue here.

I found this syntax on the internet.
Is that syntax supported?

![image](https://user-images.githubusercontent.com/33342822/129376289-d2098f93-c8ea-4b7d-a014-2acccd91596c.png)

**Comment by jaredh159** [comment]
Yes, that should work fine, since the `tw` function just returns a react native style object, you can compose them in an array just fine. (Although, note that your example has the `styles.text` _overriding_ the `text-red-500` utility.)

Is this _not_ working for you?

**Comment by sompol13** [comment]
It's working, I just to new in RN thank you for explanation.
