### ISSUE TITLE
trnc-create-styles doesn't pick tailwind.config.js

### ISSUE THREAD

**Issue by kaminskypavel** [jaredh159/tailwind-react-native-classnames#33]
Hey @jaredh159 , first of all, amazing library! 👏

I was wondering if im anything wrong , 

```
// tailwind.config.js

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      color: {
        "mygreen": "#67864A"
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}

```

then 

>$ npx trnc-create-styles

unfortunately my `tw-rn-styles.json` does not contain "mygreen".

**Comment by electroheadfx** [comment]
try colors instead of color

**Comment by kaminskypavel** [comment]
> try colors instead of color

yup that was it. totally my bad. 

thanks @electroheadfx
