### ISSUE TITLE
Feature group

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#34]
it would like nice to have group shortlang for exemple:
tw`text(center 5xl white ios:gray-800 android:pink-700)`
give : tw`text-center text-5xl text-white ios:text-gray-800 android:text-pink-700`

**Comment by jaredh159** [comment]
It's an interesting idea, and I can see your motivation for wanting it. But I'm trying to track tailwindcss pretty closely (except where RN has unique needs) -- so this feels like something that you should maybe propose over there instead. My hunch is they would not go for it, but who knows. But if it ever becomes part of tailwindcss core, I'd probably implement it here as well.
