### ISSUE TITLE
spacing config with fraction is escaped wrongly? (`p-0.5` -> `p-0\\.5`)

### ISSUE THREAD

**Issue by siebertm** [jaredh159/tailwind-react-native-classnames#35]
With a spacing config which contains a `.` (e.g. `p-0.5`, so basically all configs), the output of `trnc-create-styles` is a bit "malformed":

```jsonc
{
// ...
  "p-0\\.5": {
  }
}
```

This means that in the application code, I have to also quote this

```jsx
<View style={tw`p-0\\.5`}/>
```

The reason for this is https://github.com/jaredh159/tailwind-react-native-classnames/blob/3f5fdda65d66bb9cadeb4d130cc2c4d422e12897/src/create-styles.ts#L53, more specifically `.replace('\\/', '/')`, which should be `.replace('\\', '/')` instead I believe

**Comment by jaredh159** [comment]
Fixed by #36.
