### ISSUE TITLE
error in compile

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#37]
I have this error Iam not sure to understand:

 > npx trnc-create-styles
Starting generation of tailwind styles...
node:internal/modules/cjs/loader:930
  throw err;
  ^
Error: Cannot find module 'tailwindcss/plugin'
...

thanks

**Comment by jaredh159** [comment]
is your repo open source? if not, can you make a minimal reproduction of the problem? i think i'd need to see your package.json and your tailwind config at least

**Comment by electroheadfx** [comment]
Yes I use your toy for the company where I work now. Code its private, but I can show my configs:

package json :
https://bin.fuelphp.com/snippet/view/PV
for package.json I tried to fix adding "react-native-tailwindcss", because it was missed, but I have the same error. 

tailwind config :
https://bin.fuelphp.com/snippet/view/PW

thanks

**Comment by electroheadfx** [comment]
I fixed it when I installing a plugin : npm i -S @tailwindcss/aspect-ratio
maybe it init the plugin folder ?
all work now
