### ISSUE TITLE
android/ios for elevation/shadow

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#38]
Hey I am figure how Manage shadow both to android and iOS, it may not managed from tailwind, so I do a component and pass elevation props:

const xstyle = tw.style(
    elevation && {
      shadowColor: 'black',
      shadowOffset: { width: 0, height: elevation },
      shadowRadius: elevation * 2.5,
      shadowOpacity: 0.3,
      zIndex: elevation,
      elevation: elevation
    }
  );

Work in iOS but in android I got an error:
Erro while updating property 'elevation' of a view managed by; RCTView

Java.lang.String cannot be cast to java.lang.Double

any idea ?

thanks

**Comment by jaredh159** [comment]
I don't think this is an issue with this library, as your RN style is just getting passed straight through to RN.  If you read the error carefully, you'll see android is expecting a Double (a number), and you passed it a string.  Check the RN docs, elevation takes a `number`: https://reactnative.dev/docs/view-style-props#elevation-android
