### ISSUE TITLE
Where is the license?

### ISSUE THREAD

**Issue by knoll3** [jaredh159/tailwind-react-native-classnames#39]
I couldn't find a license on this repository. Am I missing it? 

Keep in mind when there is no license on a repo then the code is not opensource. 

From Github: 

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license

**Comment by jaredh159** [comment]
license is MIT, see package.json:

https://github.com/jaredh159/tailwind-react-native-classnames/blob/master/package.json#L7
