### ISSUE TITLE
Great library, any difference to tailwind-rn and upcoming 2.0 ?

### ISSUE THREAD

**Issue by iangregsondev** [jaredh159/tailwind-react-native-classnames#40]
Hi,

looks like a great library, i noticed you said you took inspiration from https://github.com/vadimdemedes/tailwind-rn

I was wondering what the pros/cons are in your opinion of your library of the aforementioned one ?

I also saw that you are developing v2.0 - is this in some kind of branch ? I couldn't find it. Or is it a private branch?

Thanks in advance

**Comment by jaredh159** [comment]
tailwind-rn is a great library.

when i started using it in a RN project, I made a wrapper around it which added:

- `classnames` style api for conditional classes, passing classes in multiple formats, etc.
- a tagged-template function for terser syntax
- platform prefixes
- the ability to pass through arbitrary RN styles if tailwind-rn didn't support something

those were the main four things i added to tailwind-rn for myself, and then decided my wrapper would be useful to other folks, so I worked on it a bit and open-sourced it as this library.

the v2 branch is not up publicly on github yet, it's not usable at this point, but i think i'm going to have an alpha out, possibly within a week or so.
