### ISSUE TITLE
missing '}' in compilation

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#41]
I dont understand when I compile I get this error:
Error generating tailwind styles file
Error: undefined:25049:3: missing '}'

I can't track the issue in the tailwind.config.js it seem fine
maybe I forgot something in an another file? any idea ?

https://bin.fuelphp.com/snippet/view/PX

thanks

**Comment by jaredh159** [comment]
I'm not sure, to be honest. If i could see the full repo, maybe I could give you a pointer. I would ask myself what I most recently changed before the error happened, try undoing that, and go step by step, creating the config each time, until the error happened, to isolate the issue.

**Comment by electroheadfx** [comment]
The compiler seem watch at the project if the color tokens are missing, so it stop if any tokens is missing in the config, so its possible there is a } mistake outside the app code.

**Comment by jaredh159** [comment]
I'm gonna close this, I don't think it's an issue with this library.  If you can get me a minimal reproduction repository, I'll re-open and dig in. Thanks!

**Comment by electroheadfx** [comment]
When I use my config in a fresh project, it compile fine. So the problem come from the application that compiler doesn't like,  not the config. My application run with eslint/airbnb so I dont see the issue from my code.

**Comment by jaredh159** [comment]
if you can recreate the problem in a minimal open source repository that i can clone and debug, i'm willing to take a look, but I'm not sure how to help you otherwise, sorry!

**Comment by electroheadfx** [comment]
yeah no problem, I was just testing, it config work in a blank project so I can get the rn file compiled. When I found the issue i will report it. Thanks man for your work for react-native-classnames :)
