### ISSUE TITLE
Applying Background Opacity affects same colour globally (v2)

### ISSUE THREAD

**Issue by Akumzy** [jaredh159/tailwind-react-native-classnames#45]
Using 
```
tw`bg-white bg-opacity-30`

```

affects every other `bg-white` output in the entire app.

**Comment by jaredh159** [comment]
whoops, that sounds like caching gone awry.  i'll take a look. thanks for reporting it 👍

**Comment by Akumzy** [comment]
@jaredh159 You're doing a very nice job, Jisie ike 😀

**Comment by jaredh159** [comment]
fixed in `2.0.0-alpha.6`
