### ISSUE TITLE
create tailwind config mutation

### ISSUE THREAD

**Issue by oste** [jaredh159/tailwind-react-native-classnames#46]
I am noticing interesting behavior where the tailwind config is mutated when running `create(config);` more than once. I am using RNW and each page refresh calls the `create` function. When I log to the console like this:

```
  const config = require(`../tailwind.config`);
  console.log(config);
  const tw = create(config);
```

Notice the following logs where `theme.fontFamily.sans` seems to be removed on the second run.

first page refresh:

```
{
  purge: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    fontFamily: { sans: [Array], serif: [Array] },
    extend: { spacing: [Object], borderRadius: [Object] }
  },
  variants: { extend: { borderColor: [Array], opacity: [Array] } }
}
```

second page refresh:
```
{
  purge: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    fontFamily: { sans: [], serif: [Array] },
    extend: { spacing: [Object], borderRadius: [Object] }
  },
  variants: { extend: { borderColor: [Array], opacity: [Array] } }
}
```

**Comment by oste** [comment]
Fairly certain the issue happens here https://github.com/jaredh159/tailwind-react-native-classnames/blob/v2/src/resolve/font-family.ts#L18

Could this be changed to `const firstFamily = configValue[0]` ?

**Comment by jaredh159** [comment]
Yup, changed in `2.0.0-beta.2`.

Are you calling `create()` in its own file, or in a Component file somewhere?  It's meant to be called once and then exported as a default from a configuration file.  This allows it to act as a sort of singleton for the system, and should not get re-called over and over.

That said, if you're using RN web and have HMR going, all bets are off, the HMR might be causing it to get called multiple times.

Either way, I modified it to be non-mutating.  Thanks for the issue.

**Comment by oste** [comment]
That worked. Thanks!

Yeah, still trying to get a feel for the stability with RNW and next.js. I was able to use `getStaticProps` to make sure the `tw` helper is only called on the server which removes the extra 70kb from the final build. So far it's shaping up to be a pretty awesome stack.
