### ISSUE TITLE
trnc-create-styles does not generate for tw.color

### ISSUE THREAD

**Issue by rolandknight** [jaredh159/tailwind-react-native-classnames#47]
The json style generator only generates styles for tw.style.calls not tw.color calls. For example:
tw.color('primary-text') will not work unless there is also a tw.style('bg-primary-text') call present which triggers the json style generation.

**Comment by jaredh159** [comment]
Yeah, that's how it is currently designed to work.  I think the assumption is that you configged your colors in the `colors` portion of `tailwind.config.js`, which then would automatically cause the `bg-<color>` utilities to be created.

Are you doing something non-standard? Or how do you have a color that's not generating associated `bg-` utilities?  Do you have `backgroundColor` disabled in your tailwind config?

**Comment by rolandknight** [comment]
Maybe I'm missing something here. I do have the custom colors defined in
tailwind.config.js and backgroundColor is not disabled but if I reference a
custom color from tw.color it is not generated in tw-rn-styles.json. Adding
a reference from tw.style will trigger generation. For example:

Calling tw.color('primary-text') generates this error: `bg-primary-text` is
not a valid Tailwind class name
Also calling tw.style('bg-primary-text') then tw.color("primary-text")
returns the correct color.

Maybe I'm missing something here?

**Comment by electroheadfx** [comment]
why you call the color primary-text if you want use like a color ? maybe its create a conflict with tailwind config, 
I had this issue when I called a color 'base'. Tailwind use text-base, so when I wanted color a text to base.
maybe Try to avoid the text in primary ?
can you show us your config ?

**Comment by jaredh159** [comment]
@rolandknight yeah, maybe can you post your `tailwind.config.js` so I can try to replicate?  And you're not using the v2 beta are you?

**Comment by jaredh159** [comment]
gonna close this for now. if you are still having trouble and can post some more details, i'm happy to re-open.
