### ISSUE TITLE
{ fontFamily: 'inherit' } utilty helper

### ISSUE THREAD

**Issue by oste** [jaredh159/tailwind-react-native-classnames#49]
React Native web is opinionated in how it applies a root font to all `Text` elements. After checkign RNW docs and twitter mobile source code it seems the recommended approach to override this is to apply a font to a wrapper `View` and then apply `{ fontFamily: 'inherit' }` to the inner `Text` elements. So it would look like something like this.

```
const styles = {
    wrapperView: { ...tw`font-sans text-left` },
     innerText: {
      ...{ fontFamily: 'inherit' },
      ...tw`text-base text-indigo-600 font-semibold tracking-wide uppercase`,
    },
}
```

I was hoping a utility/helper can be added for applying `fontFamily: inherit` such as `font-inherit`. This way the above code could be changed to:

```
const styles = {
    wrapperView: { ...tw`font-sans text-left` },
     innerText: {
      ...tw`font-inherit text-base text-indigo-600 font-semibold tracking-wide uppercase`,
    },
}
```

**Comment by jaredh159** [comment]
Have you tried adding the utility as described here?

https://github.com/jaredh159/tailwind-react-native-classnames/tree/v2#adding-custom-classes

**Comment by oste** [comment]
The below allowed the desired code snippet above to work. I did have to restart my dev server for the change to be seen. As another enhancement for web it would probably make sense to add some kind of watcher on that file.

```
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        'font-inherit': {
          fontFamily: 'inherit',
        },
      });
    }),
  ],
```

Another note: I think there is a typo in the docs you linked above. It should be 

```
module.exports = {
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        btn: {
          padding: 3,
          borderRadius: 10,
          textTranform: `uppercase`
          backgroundColor: `#333`,
        },
        'resize-repeat': {
          resizeMode: `repeat`
        }
      });
    }),
  ],
};
```

**Comment by oste** [comment]
I would also note that I still think adding the above utility to the library would make sense. It's a utility that will be needed for anyone trying to implement font family correctly on web.
