### ISSUE TITLE
 Error: Cannot find module 'x-chalk' Require stack:

### ISSUE THREAD

**Issue by Akumzy** [jaredh159/tailwind-react-native-classnames#5]
Running `npx trnc-create-styles` is causing an error

```log

node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'x-chalk'
Require stack:

```

**Comment by jaredh159** [comment]
@Akumzy whoops, sorry, forgot that the deps for the npx script need to not be dev, which didn't burn me locally.

1.0.1 is out now, should fix the problem.
