### ISSUE TITLE
V2 Feature Request: Add support for a "web" prefix

### ISSUE THREAD

**Issue by smlarkin** [jaredh159/tailwind-react-native-classnames#50]
A possible use case for this package might be styling across mobile (iOS + Android) and Web with [React Native Web](https://necolas.github.io/react-native-web/).

It's great that the subset of CSS that [Yoga](https://yogalayout.com/) provides should work fine on the web with TWRNC if RNW is installed.

But it would be ideal if a user could proactively target Web vs iOS/Android like so:

```javascript
tw`ios:pt-4 android:pt-2 web:pt-8`;
```

**Comment by jaredh159** [comment]
So, v2 technically already supports a `web` prefix, if that's what is returned from `Platform.OS` from `'react-native'`. It will correctly only apply the styles when the platform is web.

The bigger issue is that the web has many more styles than native supports, which are not a goal (currently) of this library to support.  So, while the `web:` prefix works, utilities like `grid` and other things without native support aren't implemented.  But if you're happy using the subset that is supported, go ahead and use the `web:` prefix.

The reason I don't really want to support all of the web utilities is that I basically had to re-write the whole tailwind JIT compiler, which is a large task -- even with only supporting what RN native supports.  I don't really have the time or inclination right now to exhaustively go through and add all of the web-only utilities.

That said, v1 of this library is not JIT-style -- it actually parses CSS with `postcss` and so it should support many more of the web utilities, so you could try v1. Although it doesn't have dark mode, and media-queries, and all the other new stuff in v2.

Or, maybe `tailwind-rn` might be a better choice, I think they might be trying to support the whole web platform as well.

**Comment by smlarkin** [comment]
Thanks @jaredh159 ... I'm perfectly happy with the subset of web APIs that `react-native-web` maps to :)

**Comment by jaredh159** [comment]
ok, good to know, glad it's working for you 👍
