### ISSUE TITLE
V2 Beta: Error running npx trnc-create-styles - 'trnc-create-styles@latest' is not in this registry

### ISSUE THREAD

**Issue by CarliBotes** [jaredh159/tailwind-react-native-classnames#52]
Note: I'm using the V2 Beta

When running `npx trnc-create-styles`, I am getting the following error: 

```
Not Found - GET https://registry.npmjs.org/trnc-create-styles - Not found
'trnc-create-styles@latest' is not in this registry.
You should bug the author to publish it (or use the name yourself!)
```

![image](https://user-images.githubusercontent.com/10037553/134997307-08294489-c7bc-45b3-90bf-28f9ab1d1518.png)

**Comment by jaredh159** [comment]
@CarliBotes there is no `trnc-create-styles` command in v2, it takes a totally different approach -- it doesn't create a `.json` file ahead of time, it parses the class names on the fly.

See the [customization](https://github.com/jaredh159/tailwind-react-native-classnames/tree/v2#customization) and [migrating from v1](https://github.com/jaredh159/tailwind-react-native-classnames/tree/v2#migrating-from-v1) section of the v2 readme for more.
