### ISSUE TITLE
V2 Feature Request: Support for JIT mode to work with Border Radius :thinking:

### ISSUE THREAD

**Issue by Karthik-B-06** [jaredh159/tailwind-react-native-classnames#53]
JIT mode enabled with Border Radius seems to be missing
```
rounded-[30px]
```

Gives a warning like this : 
<img width="321" alt="Screenshot 2021-09-29 at 7 13 33 PM" src="https://user-images.githubusercontent.com/35562287/135280625-9ccde407-7417-49b6-b885-e6e62f0d8f06.png">

**Comment by jaredh159** [comment]
thanks for the request. this is implemented in `v2.0.0-rc.1`
