### ISSUE TITLE
Value "auto" in width doesn't work

### ISSUE THREAD

**Issue by mjr** [jaredh159/tailwind-react-native-classnames#56]
In version 2.0

```javascript
<Button style={tw`w-auto`} />
```

![photo1633447828](https://user-images.githubusercontent.com/9324986/136055149-02f6a512-9544-4b37-9572-d0a581593e46.jpeg)

**Comment by jaredh159** [comment]
yeah, this was an oversight.  i've got it fixed now, and I’ll get a release out shortly.  thanks for reporting it.
