### ISSUE TITLE
V2 Customization 

### ISSUE THREAD

**Issue by dennisbouwpas** [jaredh159/tailwind-react-native-classnames#63]
Hi! 
I created tailwind.config.js file and then used it in my tailwind.js file

```javascript
module.exports = {
  theme: {
    colors: {
      primary: '#5c6ac4',
      secondary: '#ecc94b',
    }
  }
}
```

```javascript
// lib/tailwind.js
import { create } from 'twrnc';

// create the customized version...
const custom_tw = create(require('../tailwind.config.js')); // <- your path may differ

// ... and then this becomes the main function your app uses
export default custom_tw;
```

When I was trying to use my custom colors, I get **`primary` unknown or invalid utility**
Am I doing something wrong ?

```javascript
import * as React from 'react';
import { Text, View } from '../components/Themed';
import { RootTabScreenProps } from '../types';
import custom_tw from '../lib/tailwind';

export default function TabOneScreen({ navigation }: RootTabScreenProps<'TabOne'>) {
  return (
    <View style={custom_tw.style('primary')}>
      <Text style={custom_tw`text-2xl`}>Hello</Text>
    </View>
  );
}
```

**Comment by dennisbouwpas** [comment]
> The issue here is that a color name by itself (like `primary`) is not a valid tailwind utility. Colors in tailwind are used within other utility classes, like `text-primary` or `bg-primary`, etc.
> 
> If you just want the raw color value from your config, `twrnc` exposes a `color` method: `tw.color('primary')`, but I don't think that's what you want here.

You mean something like this correct ?

```javascript
module.exports = {
  theme: {
    colors: {
      'bg-primary': '#5c6ac4',
      'bg-secondary': '#ecc94b',
    }
  }
}
```

**Comment by nenjamin2405** [comment]
Hi @dennisbouwpas @jaredh159, I upgrading to V2 and using exact configuration like @dennisbouwpas, but it still shows the warning message `primary unknown or invalid utility` when I use `tw`bg-primary`. I'm confused now and need to choose between V1 and V2
