### ISSUE TITLE
borderTopRadius is not a valid prop

### ISSUE THREAD

**Issue by AshotN** [jaredh159/tailwind-react-native-classnames#65]
When using `rounded-t-xl` or `rounded-b-xl` on an `<Image>` nothing happens. 

The error I get is

`Warning: Failed prop type: Invalid props.style key 'borderTopRadius' supplied to 'Image'`

**Comment by jaredh159** [comment]
Ahh, yup, I see. Fixed in `2.0.1`. Thanks for reporting the issue.
