### ISSUE TITLE
Version 2.0.1 not available on  npm/yarn

### ISSUE THREAD

**Issue by afkcodes** [jaredh159/tailwind-react-native-classnames#67]
tried to install from npm/yarn was getting v1.5.1. tried with girhub repo too but was throwing some error. Please tell me if i am doing something wrong or its not on npm now.

**Comment by jaredh159** [comment]
yeah, sorry for the confusion, i changed the package name for version 2, but maybe should make that more clear in the docs. the new package name is `twrnc`.
