### ISSUE TITLE
No shadow support?

### ISSUE THREAD

**Issue by sankhadeeproy007** [jaredh159/tailwind-react-native-classnames#7]
It's a great library and I'm using it for my current project. Any reason why it doesn't support shadow though?
https://github.com/TVke/react-native-tailwindcss#shadows
Here's an example fo another library implementing it.

**Comment by jaredh159** [comment]
Yeah, I think I'm going to take a crack at this soon.  I do feel a little funny about arbitrarily mapping to some android `elevation` number though. Not sure that's a great approach that will work for all. I wonder if it wouldn't be better to just translate shadow for iOS and then let the developer add a specific elevation for android if they want it.  

Either way, I think at least on the ios side it makes sense to try to support box-shadow classnames, and I plan to experiment with it soon, or I'd be happy to look at a PR.

**Comment by jaredh159** [comment]
Hey, I've added basic box-shadow/elevation support in `1.2.0`.  It isn't the most flexible with custom tailwind config overrides, but it should get the job done for most use-cases, and you can always drop into passing explicit RN styles if you need more granular control.

**Comment by sankhadeeproy007** [comment]
Thanks!
