### ISSUE TITLE
Question - custom class styling definition

### ISSUE THREAD

**Issue by thijs-qv** [jaredh159/tailwind-react-native-classnames#76]
Hey Jared, maybe a bit of a left field question, but in the docs I see two ways of defining the style of a custom class:

using CSS-in-JS:
```
module.exports = {
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        btn: {
          padding: 3,
          borderRadius: 10,
          textTranform: `uppercase`,
          backgroundColor: `#333`,
        },
        'resize-repeat': {
          resizeMode: `repeat`,
        },
      });
    }),
  ],
};
```

Using a string of other utility classes:
```
module.exports = {
  plugins: [
    plugin(() => ({ addUtilities }) {
      addUtilities({
        btn: `px-4 py-1 rounded-full bg-red-800 text-white`,
        'body-text': `font-serif leading-relaxed tracking-wide text-gray-800`,
      });
    }),
  ],
};
```

Is it possible to combine these two methods? Something like:
```
module.exports = {
  plugins: [
    plugin(() => ({ addUtilities }) {
      addUtilities({
        btn: [`px-4 py-1 rounded-full bg-red-800 text-white`, {textTranform: `uppercase`}],
        'body-text': `font-serif leading-relaxed tracking-wide text-gray-800`,
      });
    }),
  ],
};
```

**Comment by jaredh159** [comment]
Ok, thanks, now I understand better.

No, not currently possible to mix the two approaches.  I suppose if enough people seemed interested in it, I might think about implementing it.  Maybe I'll leave the issue open for a while to see if it garners some upvotes.

But, without that feature, you can still implement whatever custom utilities you want, you may just need to write them in 100% css-in-js style if you can't compose them from other utilities.

**Comment by thijs-qv** [comment]
Yeah, I understand you can just use css-in-js style to create a custom class. Thought the combining of the two would maybe be a nice way to avoid rewriting styles already present in other utility classes. Thanks!
