### ISSUE TITLE
Hover

### ISSUE THREAD

**Issue by axeldelafosse** [jaredh159/tailwind-react-native-classnames#79]
Hey Jared!

Thank you so much for your work. This is amazing.

I'm thinking about a way to use the `hover` utility. Maybe we could have a function like `tw.color()` but `tw.hover()`?

I'm using Moti for animations and interactions: https://moti.fyi. We could use the `tw.hover()` function manually to parse the styles to apply when hovered and pass them via the animate prop in [MotiPressable](https://moti.fyi/interactions/pressable) (for example).

What do you think? cc @nandorojo would love to have your opinion too!

**Comment by axeldelafosse** [comment]
Yes indeed, I'm building a universal design system that works on iOS, Android and Web.

OK I'll send a PR ;) Thanks!

**Comment by nandorojo** [comment]
> We could use the tw.hover() function manually to parse the styles to apply when hovered and pass them via the animate prop in MotiPressable (for example).

This could work, but you’d have to define your hovered & non-hovered styles outside of the `animate` prop since it’s a worklet.

**Comment by jaredh159** [comment]
I'm going to close this for now. If you end up wanting to tackle this in a PR, I'm open to considering it. Thanks!
