### ISSUE TITLE
What really happens to the unused properties in tw-rn-styles.json during build?

### ISSUE THREAD

**Issue by Akumzy** [jaredh159/tailwind-react-native-classnames#8]
I don't know if there is any tree shaking or purging unused generated styles properties which I'm kinda concern about

**Comment by jaredh159** [comment]
I'm not really sure -- I took this approach from https://github.com/vadimdemedes/tailwind-rn, and they don't seem to do any purging.

Is purging or tree-shaking necessary in a RN project? What's the downside, other than a few KB being added to the final compiled output for the json file? Maybe there is a downside, I just can't see it at the moment. Perhaps there is a small runtime speed improvement that could be found if the lookup map was smaller, but I'm really not sure it would be noticeable.

I'd definitely be curious to know if you had more expertise into this, and could explain any holes in my understanding.

**Comment by Akumzy** [comment]
Fair points regarding the file size, Actually I really didn't know it's possible to use Tailwind with React Native that's why I'm asking.
