### ISSUE TITLE
export TwConfig as a type

### ISSUE THREAD

**Issue by oste** [jaredh159/tailwind-react-native-classnames#85]
It would be useful for my application if I can use the `TwConfig` type. Can this be exported?

Note: I am trying to use the type in a utility function that gets passed TwConfig and then `create`

**Comment by jaredh159** [comment]
yeah sure, `v2.0.6` will contain the export, available in a few minutes.  Just be aware that that type is not meant to be a perfect reflection of a tailwind config object, which is partly why I didn't export it as part of the public interface of the library to start.  It's basically a type that is accurate enough for me to get good type safety around the parts of the tailwind config that the internal functions use.  So, if you try to use it to model a full tailwind config, you might find it doesn't type check.  But it seems like that's not what you're doing, so I think for your use case, it'll be fine.
