### ISSUE TITLE
In case of using custom style all the following styles are ignored

### ISSUE THREAD

**Issue by keshavmahawar** [jaredh159/tailwind-react-native-classnames#88]
Hi!!
when using and custom utility following it are ignored on the first run(not cached)
## Example:
custom utility
```
caption: 'text-sm font-700'
```
usage
```
tw`caption text-disabled mt-1 mb-0.5`
```
all the styles like `text-disabled mt-1 mb-0.5` are ignored

## Reason
in `index.ts`
```javascript
    for (const utility of utilities) {
      let styleIr = cache.getIr(utility);
      if (!styleIr) {
        if (utility in customStringUtils) {
          const customStyle = style(customStringUtils[utility]);
          cache.setIr(utility, complete(customStyle));
          return customStyle;
        }
        const parser = new ClassParser(utility, config, cache, device);
        styleIr = parser.parse();
      }
}
```
in case of encountering `customStyle` style is returned directly,it  should be something like 
```javascript
 resolved = {...resolved,...customStyle}
 continue;
```
instead of `return` in my opinion

**Comment by jaredh159** [comment]
thanks for the report, you're right -- the problem was where you said it was and the fix recommended was correct as well.

Fixed in `v2.0.7`.
