### ISSUE TITLE
Global font override?

### ISSUE THREAD

**Issue by AshotN** [jaredh159/tailwind-react-native-classnames#89]
Would it be possible to do a global font override?

**Comment by jaredh159** [comment]
I'm not sure what you mean. Can you give additional context? Motivation, use case, code samples, etc?

**Comment by AshotN** [comment]
It's a rather abstract question as I don't really know how to attempt it.

But if I have a whole app built lets say, and I wanted to override the default font with something like Roboto or Open Sans or whatever. 

Is there a way to do it without having to specify the font each time on every `<Text>` element

**Comment by jaredh159** [comment]
I think the recommended best practice for that is to make your _own_ `<Text />` component, which includes the font you want to use, which is just a wrapper around RN's `<Text />` component, and import and use your own version all over your app.

**Comment by AshotN** [comment]
That's what I figured, was wondering if there were a better solution. Thanks again!
