### ISSUE TITLE
Custom classnames not working

### ISSUE THREAD

**Issue by Onibenjo** [jaredh159/tailwind-react-native-classnames#99]
I keep getting 
``` 
`btn` unknown or invalid utility
```

My tailwind.config.js:
``` tailwind.config.js
/* eslint-disable @typescript-eslint/no-var-requires */
const {plugin} = require('twrnc');

export const theme = {
  screens: {
    sm: '380px',
    md: '420px',
    lg: '680px',
  },
  extend: {
    spacing: {
      518: '518px',
    },
    colors: {
      primary: '#D8383A',
      'gray-black': '#010101',
      'grey-black': '#010101',
      'sonic-silver': '#747474',
      success: '#2D9CDB',
      info: '#2D9CDB',
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    plugin(({addUtilities}) => {
      addUtilities({
        // 😎 similar to `@apply`
        btn: `bg-primary w-full rounded-3xl py-[15px]`,
      });
    }),
  ],
};

**Comment by jaredh159** [comment]
Hmmm... that `tailwind.config.js` looks funny to me.  You're just doing a named export of `theme`, when I think you need it to be the default export.  I've never seen a config that looks like that, all of mine always do the commonjs style `module.exports = {...}` like on the tailwind docs site. I can't say 100% that's the problem, but can you switching to the more normal way of exporting the config and see if that fixes it?

**Comment by Onibenjo** [comment]
Oh, it worked.. Surprisingly, it worked with the named export for the colours and spacing

**Comment by gamble23** [comment]
Hi, sorry for reopening but right now i facing the same problem.

I created my **_tailwind.config.js_** file inside root and added this:

```javascript
const { plugin } = require('twrnc'); 

module.exports = {
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        test: {
          backgroundColor:  "red",
        },
      });
    }),
  ],
};
```

And then try to use it:
```
<ScrollView style={tw`test`}>
  <Text>Test</Text>
</ScrollView>
```

Still getting this error 
`"test" unknown or invalid utility`

I created my App with expo wich seems to use this version of react native`"react-native": "0.64.3"`
My node version is (16.13)

Anything that i forgot or misunderstood? I hope someone can help me.
